### PR TITLE
Change variant wl_ in Nodes from double to float

### PR DESCRIPTION
**Pull request by nguyenpham**
**Edited:** 
The PR:
- add a warning comment for the variant wl_ in Node class
- changes the return type of the function GetWL from float to double and do clear castings if needed

Discuss: the original function GetWL is a data bottleneck for the variant wl_ since sometimes the engine has to keep converting from double to float then back to double, losing both computing and precision. We should keep the data unchanged type as long as possible to maximize the benefit of changing from float to double for wl_

**Origin:**
Using double for the variant wl_ (in the class Nodes) is redundant both on size and computing (for converting) since all in/out and operations with other variants using floats only.

By changing from double to float the precisions of all functions are almost the same but we can reduce the size of Nodes from 80 (for 64-bit system) to 72 bytes, a 10% decreasing.

### CODE REVIEW

**Comment by ddobbelaere** [comment]
If you are wondering why we use double, please check out #1280 and #875.

Maybe it's a good idea to discuss "holy grail solutions without any apparent drawback" in Discord chat #dev or #dev-public first, because more likely than not there is a drawback/good reason for it :P.

**Comment by nguyenpham** [comment]
Oh I see. Look like I am reinventing the wheel or even worse, trying to destroy it ;)
Thanks for the info. Reading...

**Comment by ddobbelaere** [comment]
No problem (and no offense meant), I think it is very much appreciated to have multiple critical eyes looking at the codebase and taking nothing for granted...

**Comment by borg323** [comment]
Actually, can you re-purpose this pr into one adding a comment with a pointer to the relevant discussion?

**Comment by nguyenpham** [comment]
@borg323: can you help to do that, I don’t know how to do. Thanks a lot

**Comment by borg323** [comment]
Just saying "This has to be a double" with a link to #875 should be enough

**Comment by nguyenpham** [comment]
Sorry, I totally lost. Do you mean just edit the introduction/explanation of this PR (so it’s still a PR) or add a new issue about this one?

**Comment by borg323** [comment]
I meant change this pr to one just adding the above comment to node.h, so I can review it quickly.

**Comment by liamlim** [comment]
Just revert all changes in this PR and add explaining comment to definition of _wl which says that this variable must be double and also mentions #875. Then everyone who wants to touch this part of code in future will know the reasons why it has to be double

**Comment by nguyenpham** [comment]
Oops, got it now. How silly of me!

**Comment by nguyenpham** [comment]
I have committed:
- revert all changes
- add a comment for variant wl_ (as the suggestion by @borg323)
- change the return type of the function GetWL from float to double, do clear castings if needed

IMO, the original function GetWL is a data bottleneck for the variant wl_ since sometimes the engine has to keep converting from double to float then back to double, losing both computing and precision. We should keep the data unchanged type as long as possible to maximize the benefit of changing from float to double for wl_

**Comment by borg323** [comment]
There were at least two earlier PRs doing something similar: #878 and #349

**Comment by nguyenpham** [comment]
IMO, it is quite different since the PR didn't touch to any variants, only return type of a function. That deals with operations in temporary memory only

**Pull request closed without merging**
