### PR TITLE
Trade penalty per Node

### PR DESCRIPTION
**Pull request by nblaxall**
Add trade-penalty to search

### CODE REVIEW

**Comment by nblaxall** [comment]
With the help of jjosh and Videodr0me I changed the trade-penalty (piece trade "contempt") to change in depth of search, because the original seemed to only include the total piece count at root and didn't change.
I played around with different values, and "contempt = 0.005 * (node_to_process->piececount - 32);" seemed to help the most so far.  I also flip the value depending on whose move it is.

```   # PLAYER                :  RATING  PLAYED   (%)  CFS(%)    W    D     L  D(%)  OppN
   1 11248-tp005_-+_-32    :     366     530  88.8      89  414  113     3  21.3     1
   2 11248-tp010_-+_-32    :     336     408  87.0      97  313   84    11  20.6     1
   3 11248                 :     296     534  84.2     100  374  151     9  28.3     1
   4 laser                 :       0    1472  13.4     ---   23  348  1101  23.6     3

Head to head statistics:

1) 11248-tp005_-+_-32 366 :    530 (+414,=113,-3),  88.8 %

   vs.                      :  games (   +,   =, -),   (%) :   Diff,   SD, CFS (%)
   laser                    :    530 ( 414, 113, 3),  88.8 :   +366,   16,  100.0

2) 11248-tp010_-+_-32 336 :    408 (+313,=84,-11),  87.0 %

   vs.                      :  games (   +,  =,  -),   (%) :   Diff,   SD, CFS (%)
   laser                    :    408 ( 313, 84, 11),  87.0 :   +336,   18,  100.0

3) 11248              296 :    534 (+374,=151,-9),  84.2 %

   vs.                      :  games (   +,   =, -),   (%) :   Diff,   SD, CFS (%)
   laser                    :    534 ( 374, 151, 9),  84.2 :   +296,   14,  100.0

4) laser                0 :   1472 (+23,=348,-1101),  13.4 %

   vs.                      :  games (  +,   =,    -),   (%) :   Diff,   SD, CFS (%)
   11248-tp005_-+_-32       :    530 (  3, 113,  414),  11.2 :   -366,   16,    0.0
   11248-tp010_-+_-32       :    408 ( 11,  84,  313),  13.0 :   -336,   18,    0.0
   11248                    :    534 (  9, 151,  374),  15.8 :   -296,   14,    0.0```

**Comment by zz4032** [comment]
@mooskagh 
It depends on the opponent's strength, if trading pieces is favorable. This is part of the concept of contempt. And this information (if opponent is stronger) can only be provided by the user because the engine can not know about it or learn for it.

In case of opponents of equal strength (not related to contempt) it still makes sense to have an "avoid trading" penalty for the winning side. I agree the engine should find it out by itself, but it requires too look far ahead and have knowledge about the endgame.

**Comment by ddobbelaere** [comment]
From a "puristic" point of view, the cleanest solution is to let the NN decide on everything, including trading down pieces.

Moreover, I disagree with the statement that you should tweak the behavior depending on the opponent. Suppose you are a chess truth oracle, you just play (one of the) best moves, irrespectively. I am not claiming Leela is such an oracle already, but why not try to aim for that in a consequent zero spirit?

**Comment by zz4032** [comment]
Because chess starts with score 0.0 and even a perfect engine could run into a 3-fold draw. Would a human grandmaster ever do this to a chess rookie?
Contempt was the reason why Stockfish 9 started dominating chess tournaments.

Btw I don't know why the zero concept is still floating around. Even the bugged test10 networks on good GPUs are stronger vs. crippled Stockfish 8 than Alpha Zero on Google's hardware.

**Comment by ddobbelaere** [comment]
Let's indeed say chess is a draw (and you know it as an oracle), I didn't say that you have to make life easy for your opponent by going to the quickest 3 fold rep.

It is perfectly possible that you play like a perfect engine, but try to maximize the possibility for your (imperfect) opponent to go astray. Keeping pieces on the board is most likely a good strategy to do that, but why not let Leela find that out by herself?

**Comment by hans-ekbrand** [comment]
As ddobbelaere points out, playing training games only against an opponent with the same strength as yourself will never teach Leela to maximise Elo in tournament settings. If we want Leela to really behave like human, and take the strength of the opponent into account, the right way of doing it would be to provide Elo of opponent as input to the NN and include weaker versions of herself in training, and - during tournament play - include opponent Elo in the UCI protocoll. However, the UCI protocoll is what it is and not up to us to change, so while a zero solution would be possible and preferable, it is not likely to happen. However, all non-zero patches of playing behaviour should be also be thoroughly tested against SF-dev, since the goal is to be best, not to beat laser more convincingly.

**Comment by zz4032** [comment]
```
   # PLAYER           :  RATING  ERROR   GAMES  WON  DRAWN  LOST  DRAWS(%)  OppN
   1 lc0-536-tuned    :     317     35     500  396     67    37      13.4     1
   2 lc0              :     317     38     500  388     83    29      16.6     1
   3 lc0-536          :     302     36     500  381     86    33      17.2     1
   4 stockfish        :       0   ----    1500   99    236  1165      15.7     3
```
"lc0-536-tuned" is with parameters from the tuning I did resulting in:
`auto contempt = 0.0225 * (node_to_process->piececount - 13.1);`

**Comment by evalon32** [comment]
@hans-ekbrand The UCI protocol already has the option to pass Elo (whether it's used in any tournaments is a separate question):
> = UCI_Opponent, type string
>		   With this command the GUI can send the name, title, elo and if the engine is playing a human  or computer to the engine.

**Comment by jjoshua2** [comment]
This pr `lc0tradepenalty               ` has shown 98% LOS over defaults, enough for me to quit testing and be sure it's better at 30s games. I added it to my 30s list, its roughly identical with my PR in performance, but probably not better against Vajolet. They could both be compared to SF and this one might do a bit better, but mine also seemed to gain. Swylandia has shown me some results of his doing better against SF as well.
```ResultSet-EloRating>ratings
Rank Name                         Elo    +    - games score oppo. draws
   1 lc0contempt .0015             85   40   40   394   89%  -245   18%
   2 lc0tradepenalty               76   37   37   441   89%  -245   19%
   3 lc0contempt .0015 fpur 1.3    35   78   78    85   85%  -245   18%
   4 lc0contempt 0 fpur 1.3        28   62   62   128   86%  -245   23%
   5 lc0contempt 0                 21   35   35   394   85%  -245   25%
   6 Vajolet2_2.5 30CPU          -245   19   19  1442   12%    57   20%
ResultSet-EloRating>los
                            lc lc lc lc lc Va
lc0contempt .0015              63 86 93 99100
lc0tradepenalty             36    82 90 98100
lc0contempt .0015 fpur 1.3  13 17    55 62 99
lc0contempt 0 fpur 1.3       6  9 44    58100
lc0contempt 0                0  1 37 41   100
Vajolet2_2.5 30CPU           0  0  0  0  0```

**Comment by nblaxall** [comment]
Results so far vs SF (30s+0.5, SF only has 4 cores):

```   # PLAYER                :  RATING  PLAYED   (%)  CFS(%)    W    D    L  D(%)  OppN
   1 11248-tp005_-+_-32    :      81     204  61.3      99   67  116   21  56.9     1
   2 11248                 :      30     204  54.2      97   45  131   28  64.2     1
   3 SF9-bmi               :       0     408  42.3     ---   49  247  112  60.5     2


Head to head statistics:

1) 11248-tp005_-+_-32 81 :    204 (+67,=116,-21),  61.3 %

   vs.                      :  games (  +,   =,  -),   (%) :   Diff,   SD, CFS (%)
   SF9-bmi                  :    204 ( 67, 116, 21),  61.3 :    +81,   16,  100.0

2) 11248              30 :    204 (+45,=131,-28),  54.2 %

   vs.                      :  games (  +,   =,  -),   (%) :   Diff,   SD, CFS (%)
   SF9-bmi                  :    204 ( 45, 131, 28),  54.2 :    +30,   15,   97.2

3) SF9-bmi             0 :    408 (+49,=247,-112),  42.3 %

   vs.                      :  games (  +,   =,   -),   (%) :   Diff,   SD, CFS (%)
   11248-tp005_-+_-32       :    204 ( 21, 116,  67),  38.7 :    -81,   16,    0.0
   11248                    :    204 ( 28, 131,  45),  45.8 :    -30,   15,    2.8


LOS csv:
"N","NAME",0,1,2
0,"   11248-tp005_-+_-32",,98.9,100.0
1,"                11248",1.1,,97.2
2,"              SF9-bmi",0.0,2.8,
```

**Comment by nblaxall** [comment]
Another thing I'd like to mention, if some sort of piece trade penalty method is being tested, then probably it doesn't make sense to test it with very short TC, because it heavily depends on the search - ie trades are compared in the search, and at very short TC there'd be lots of noise, whereas the longer the TC, the more the piece trade penalty would have an effect.

I've tested at 30s + 0.5, and I wouldn't think less than this is a good idea? ... I'd like to see tests with longer TC's.

**Comment by nblaxall** [comment]
Final results vs SF (4-threads) 30s+0.5:
```
   # PLAYER                :  RATING  PLAYED   (%)  CFS(%)    W    D    L  D(%)
   1 11248-tp005_-+_-32    :      66     350  59.3     100  105  205   40  58.6
   2 11248                 :      18     350  52.6      94   75  218   57  62.3
   3 SF9-bmi               :       0     700  44.1     ---   97  423  180  60.4

Head to head statistics:

1) 11248-tp005_-+_-32 66 :    350 (+105,=205,-40),  59.3 %

   vs.                      :  games (   +,   =,  -),   (%) :   Diff,   SD, CFS (%)
   SF9-bmi                  :    350 ( 105, 205, 40),  59.3 :    +66,   12,  100.0

2) 11248              18 :    350 (+75,=218,-57),  52.6 %

   vs.                      :  games (  +,   =,  -),   (%) :   Diff,   SD, CFS (%)
   SF9-bmi                  :    350 ( 75, 218, 57),  52.6 :    +18,   11,   94.3

3) SF9-bmi             0 :    700 (+97,=423,-180),  44.1 %

   vs.                      :  games (  +,   =,   -),   (%) :   Diff,   SD, CFS (%)
   11248-tp005_-+_-32       :    350 ( 40, 205, 105),  40.7 :    -66,   12,    0.0
   11248                    :    350 ( 57, 218,  75),  47.4 :    -18,   11,    5.7

"N","NAME",0,1,2
0,"   11248-tp005_-+_-32",,99.8,100.0
1,"                11248",0.2,,94.3
2,"              SF9-bmi",0.0,5.7,
```

Will test longer TC next.

**Comment by zz4032** [comment]
Added the source code update and tuned again for **long** TC, tuned parameter values are very similar to those from short TC tuning but converged in less number of games:
`auto contempt = 0.0258 * (node_to_process->piececount - 11.1);`

Now there is clearly an improvement:
```
   # PLAYER           :  RATING  ERROR   GAMES  WON  DRAWN  LOST  DRAWS(%)  LOS(%)  OppN
   1 lc0-536-tuned    :     387     46     300  246     48     6      16.0   100.0     1
   2 lc0              :     281     34     300  203     93     4      31.0   100.0     1
   3 stockfish        :       0   ----     600   10    141   449      23.5     ---     2
```
Running "lc0-356-tuned" vs. "lc0" next....

**Comment by nblaxall** [comment]
Added parameter options for trade penalty so people can specify their own:

To be called with eg: --trade-penalty=0.0258 --trade-penalty2=11.1
(those are the defaults)

**Comment by gonzalezjo** [comment]
They should probably default to off.

**Comment by jjoshua2** [comment]
Tried zz's clop and it was so much worse I stopped it early since swylandia also was having bad early results and I have more promising things to test.
```Rank Name                          Elo     +/-   Games   Score   Draws
   0 cfish 9/9 30cpu               140      64      60   69.2%   48.3%
   1 lc0v19 11248                 -108      73      30   35.0%   63.3%
   2 lc0tradepenalty zz           -176     113      30   26.7%   33.3%```

**Comment by nblaxall** [comment]
Yea I tried ZZ's clopped results and they were worse.  I'll try with the 0.005 & 30 numbers I was using before and test again just to make sure I didn't make a mistake in the parameter options version (although testing on my test position showed it was fine).  I'll also change the parameters to default to off as gonzalezjo suggested.

**Comment by jkiliani** [comment]
Trade-penalty should probably default to off so the PR is neutral for people that don't like the concept (@mooskagh), but there isn't really a good reason not to use this in TCEC/CCC. The tunings show a rather convincing benefit in my opinion.

**Comment by navs25** [comment]
Trade Penalty is no penalty, it is an advantage!
Perhaps we should rename the concept to “Positional Complexity”
This reflects what it is doing - playing to Leela’s positional strength. (Which is the opposite of ab-engines tactical simplicity)

**Comment by zz4032** [comment]
Selfplay with my tuned values didn't go well:
```
   # PLAYER       :  RATING  ERROR   GAMES  WON  DRAWN  LOST  DRAWS(%)  LOS(%)  OppN
   1 lc0          :       0   ----     578  317    199    62      34.4   100.0     1
   2 lc0-tuned    :    -167     25     578   62    199   317      34.4     ---     1
```
Now I will try tuning 1) at selfplay and 2) at selfplay alternating with playing weaker stockfish (equal opponent and weaker opponent simultaneously).

**Comment by nblaxall** [comment]
I re-ran the 30s + 0.5 vs SF for piece of mind, because my previous test was using v19 rc5 and also didn't use the -0.9999 to 0.9999 bit ... the PR is using v19 release and it's also using:
```
  if(node_to_process->v < -1.0) {
    node_to_process->v = -0.9999;
  } else if (node_to_process->v > 1.0) {
    node_to_process->v = 0.9999;
  }
```

... the results the new 30s + 0.5 vs SF that I ran with up-to-date PR are:
```
   # PLAYER               :  RATING  PLAYED   (%)  CFS(%)    W    D    L  D(%)
   1 11248-tp0.005_-32    :      57     244  58.0      85   70  143   31  58.6
   2 11248                :      36     244  55.1     100   55  159   30  65.2
   3 SF9-bmi              :       0     488  43.4     ---   61  302  125  61.9

"N","NAME",0,1,2
0,"    11248-tp0.005_-32",,85.4,100.0
1,"                11248",14.6,,99.7
2,"              SF9-bmi",0.0,0.3,
```
So it's still good - not quite as good but still good.
Maybe the 0.9999 part isn't needed and the if statement is slowing it down a very little bit?
I'm tempted to take that if statement out.

**Comment by zz4032** [comment]
Tuning result in selfplay and vs. 300Elo weaker Stockfish simultaenously:
` auto contempt = 0.001 * (node_to_process->piececount - 27.7);`
That's much closer now to the initial values others are using. Going to try that in matches next.

**Comment by nblaxall** [comment]
I'm continuing to test this tp version with a lot of different values and ideas, but so far the one submitted to tcec keeps coming out of top (ie the 0.005 & 32 one) - at lease for short time controls, as can be seen here (30s+0.5):
```
   # PLAYER             :  RATING  PLAYED   (%)  CFS(%)    W    D    L  D(%)
   1 11248-tp_005_32    :     391     144  90.3     100  116   28    0  19.4
   2 11248              :     270     144  82.3     100   97   43    4  29.9
   3 laser              :       0     288  13.7     ---    4   71  213  24.7
```
... and if I combine that version with previous 30s+0.5 results:
```
   # PLAYER             :  RATING  PLAYED   (%)  CFS(%)    W    D     L  D(%)
   1 11248-tp_005_32    :     370     710  89.1     100  558  149     3  21.0
   2 11248              :     287     714  83.6     100  493  208    13  29.1
   3 laser              :       0    1424  13.7     ---   16  357  1051  25.1
```
(I believe jjosh & Navs are testing longer time controls.)

**Comment by nblaxall** [comment]
...and combining the 30s+0.5 tests vs SF9:
```
   # PLAYER             :  RATING  PLAYED   (%)  CFS(%)    W    D    L  D(%)
   1 11248-tp_005_32    :      56     808  57.9      98  227  481  100  59.5
   2 11248              :      31     678  54.4     100  156  426   96  62.8
   3 SF9-bmi            :       0    1486  43.7     ---  196  907  383  61.0
```

**Comment by nblaxall** [comment]
The 3-fold repitition draw: rofChade vs Lc0 TP in tcec s14 div3 2018-12-05:
1. Nf3 Nf6 2. Nc3 g6 3. e4 d6 4. d4 c6 5. Be2 Bg7 6. O-O Qc7 7. a4 O-O 8. Be3 e5 9. dxe5 dxe5 10. Qc1 a5 11. h3 Re8 12. Rd1 Bf8 13. Bg5 Nbd7 14. Bc4 Nh5 15. Qe3 Nc5 16. Bh6 Ng7 17. Qg5 Nge6 18. Qh4 Bxh6 19. Qxh6 Nf8 20. Nh2 Qe7 21. Nf3 Qc7 22. Nh2 Qe7 23. Nf3 Qc7 1/2-1/2
... standard Leela also wants to take the draw (even after a long think).

SF wants to do 22...Kg8 after a while of thinking.
The TP version also wanted to take the draw, but using --trade-penalty2=16.0 instead of 32 give contempt (ie in it makes Leela thinks she's winning by more) if the number of piece is greater than 16.
Using --trade-penalty=0.005 --trade-penalty2=16.0 avoids the repetition, and after 244313 nodes (pretty quick!) Leela settles on 22...Kg8 (see: https://pastebin.com/sQCQrj0A).

Using --trade-penalty=0.005 --trade-penalty2=16.0 instead of --trade-penalty=0.005 --trade-penalty2=32.0 tests just as well so far (not many games) using 30s+0.5:
```
   # PLAYER             :  RATING  PLAYED   (%)  CFS(%)    W    D    L  D(%)
   1 11248-tp_005_16    :     362     194  88.7      50  153   38    3  19.6
   2 11248-tp_005_32    :     362     194  88.7      99  152   40    2  20.6
   3 11248              :     269     182  82.1     100  121   57    4  31.3
   4 laser              :       0     570  13.4     ---    9  135  426  23.7
```

It's interesting that tests show there's not a lot in it for elo with values of --trade-penalty2 between 32 & 16 (and even 36 seems fine) but using 0 loses some elo, and -16 loses more, and -32 loses so much in tests that it's weaker than laser.

So it looks like --trade-penalty=0.005 is giving the penalty for trading pieces, and --trade-penalty2=16.0 is giving standard contempt (due to the calculation that's used, in the above position it would be 24 pieces - 16).

**Comment by nblaxall** [comment]
For v0.19.1-rc2 vs SF9 (30s+0.5), although it initially started out well, it has since not done so well in my test:
```
   # PLAYER                         :  RATING  PLAYED   (%)  CFS(%)    W    D    L  D(%)
   1 11248-v0.19.1-rc2              :      52     234  57.3      92   57  154   23  65.8
   2 11248-v0.19.1-rc2-tp_005_16    :      24     234  53.4      97   54  142   38  60.7
   3 SF9-bmi                        :       0     468  44.7     ---   61  296  111  63.2
```
... the number of games isn't great and so might be due to noise, but it looks as that tp isn't that helpful vs SF (even though it seemed to be for v0.19.0).

**Comment by nblaxall** [comment]
I tried v0.19.1-rc2 tp vs SF with a longer TC of 2m+2s (120+2) so that variable cpuct could kick in (and also my theory is that tp does well with deeper search):
```
   # PLAYER                         :  RATING  PLAYED   (%)  CFS(%)    W    D    L  D(%)
   1 11248-v0.19.1-rc2-tp_005_16    :      87      50  62.0      86   13   36    1  72.0
   2 11248-v0.19.1-rc2              :      50      50  57.0      99    9   39    2  78.0
   3 SF9-bmi                        :       0     100  40.5     ---    3   75   22  75.0
```
... not many games yet but at least it's promising so far.

Next I'll actually merge rc2 into this PR so others can test too.

**Pull request closed without merging**
