### PR TITLE
Minor optimizations for non-LTO builds

### PR DESCRIPTION
**Pull request by Tilps**
These methods are fairly trivial and used in or near the hottest paths of our code - so having them not be inline in the header forces LTO to be required to inline them if the compiler feels it could be a good idea - when there isn't a real compelling reason to keep them in the implementation file.

### CODE REVIEW

**Comment by borg323** [comment]
I think #1369 is a better alternative.

**Comment by Tilps** [comment]
I'll see how that goes with my debugging :)

**Comment by borg323** [comment]
I would prefer to keep the Edge::GetP() implementation together with the Edge::SetP() one (and the comment above).

**Comment by Tilps** [comment]
I actually plan on abandoning this PR - LTO being default on may not quite work with VS out of the box, but now that I know how to fix that I no longer worry about these details personally - and our release binaries use PGO anyway.

**Pull request closed without merging**
