### PR TITLE
basic line editing

### PR DESCRIPTION
**Pull request by borg323**
I seems on windows the console provides some basic line editing functionality to the uci interface. This adds it to other systems as well.

### CODE REVIEW

**Comment by mooskagh** [comment]
I wonder if:
1. We should add some more copyrights to the license file that we bundle,
2. Whether it still works fine in all non-interactive scenarios (i.e. chess GUIs)
3. Whether it doesn't slow down input..

**Comment by borg323** [comment]
> 1. We should add some more copyrights to the license file that we bundle,

We certainly should add copyrights somewhere but maybe not in the license file. However, I see we are only bundling a README with cuda, which seems like a bug. 
Moreover, I am also worried about your other two questions (and 4. MacOS portability, 5. Is it needed for android) so I didn't bother doing it before we decide that we really want this.

**Comment by mooskagh** [comment]
I thought that it may make sense to just have a wrapper tool:
Which redirects stdout and stderr to stdout and stderr.
Which provides line editing interface for stdin and then redirects it.

I've just found https://github.com/thejoshwolfe/consoline, seems to be it..

**Comment by borg323** [comment]
Yes, this is good enough.

**Pull request closed without merging**
