### PR TITLE
First move boost

### PR DESCRIPTION
**Pull request by Tilps**
I'm guessing someone will want this to be a configurable parameter.  But I doubt there is a lot of elo in tuning this, so I didn't bother...

I instead 'derived' this value by experiment - looking at the distribution of ratio of initial_nodes to total_playouts at the end of each turn across a bunch of games played under time control.
With default, there is a clear growth of that ratio over the first 3-4 moves out of book.  With the current multiplier of 3, that growth is not clear.
I didn't really expect to need a multiplier greater than 2, but 2 clearly still had a growth pattern happening.

Publishing in case someone wants to try and see if there is any elo improvement.  I don't think I have the patience :P

### CODE REVIEW

**Comment by fli** [comment]
I like this change. Should it be scaled by the pruning aggressiveness factor in some way?

**Comment by jjoshua2** [comment]
It probably should be something like 2.0 * smart pruning factor.

I was thinking that maybe ponder multiplier could be in the same scaling function as the first move scalar, but doesn't look too easy here...

**Comment by mooskagh** [comment]
I think it's somehow neater to implement by setting `time_spared_ms_` to something else than 0 in the beginning of the game.

**Comment by jjoshua2** [comment]
I heard @borg323 did some tests and this and it lost elo? Maybe this can be a hidden variable with default 1.0 so we can tune it. And then next release we will put some reasonable value there. What do you think? @Tilps

**Comment by borg323** [comment]
There is no easy/clean way to use `time_spared_ms_` since we need the adjustment to be relative to `this_move_time` that is calculated relatively late. I added some patches introducing the `--first-move-time-adj` hidden option with a lower default of 1.6 that seems OK in my tests.

**Comment by Naphthalin** [comment]
I think this is tackled in crem's smooth time manager which tries to keep nodes per move fixed over the game instead of allocated time, but I think there is no PR yet for it.

**Pull request closed without merging**
