### PR TITLE
Also translate moves to legacy format during selfplay.

### LINKED ISSUE #1009: Selfplay outputs chess960 "capture rook" moves
lczero-client converts the `gameready` moves to pgn:
https://github.com/LeelaChessZero/lczero-client/blob/33e15f9ec6ce147de76802a0d173804845de219c/lc0_main.go#L403

A quick test:
```go
convertMovesToPGN(strings.Split("d2d4 g8f6 g1f3 b7b6 g2g3 c8b7 f1g2 c7c5 e1h1", " "), "")
```
errors with:
```
movstr: chess: invalid move e1h1
```

Perhaps either https://github.com/Tilps/chess needs to get updated or selfplay should output e1c1/e1g1:
https://github.com/LeelaChessZero/lc0/blob/58428e8c3fe0113c68390343f52d3fa6a1f92907/src/selfplay/loop.cc#L120

### PR DESCRIPTION
**Pull request by mooskagh**
Fixes #1009.

### CODE REVIEW

**Comment by Mardak** [comment]
This looks to change the uci "info …" and "bestmove …" lines, but lczero-client actually grabs the final "gameready" line which outputs `move.as_string()`:
https://github.com/LeelaChessZero/lc0/blob/54a6710e4cfe6655983a1e786bc5f6f9476d87c5/src/selfplay/loop.cc#L120

I think lczero-client doesn't actually do anything with the info/bestmove prefixed lines anyway as lc0/selfplay handles playing the (temperature) moves. (?) But probably good to fix / keep consistent.

E.g.,
```
…
info player 1 gameid 0 side white depth 1 seldepth 1 time 4 nodes 1 score cp 41 wdl 571 0 429 hashfull 0 nps 250 tbhits 0 pv e1g1
bestmove e1g1 player 1 gameid 0 side white
info player 2 gameid 0 side black depth 1 seldepth 1 time 4 nodes 1 score cp -56 wdl 405 0 595 hashfull 0 nps 250 tbhits 0 pv e8g8
bestmove e8g8 player 2 gameid 0 side black
info player 1 gameid 0 side white depth 1 seldepth 1 time 4 nodes 1 score cp 44 wdl 575 0 425 hashfull 0 nps 250 tbhits 0 pv d2f4
bestmove d2f4 player 1 gameid 0 side white
info player 2 gameid 0 side black depth 1 seldepth 1 time 4 nodes 1 score cp -65 wdl 390 0 610 hashfull 0 nps 250 tbhits 0 pv d7d5
…
gameready gameid 0 play_start_ply 0 player1 white result draw moves … e1h1 e8h8 d2f4…

**Comment by Tilps** [comment]
yeap gameready is the one that matters.

**Comment by mooskagh** [comment]
Updated to also handle `gameready`.

**Comment by borg323** [comment]
What about changing it to something like the following?
```diff
diff --git a/src/selfplay/game.cc b/src/selfplay/game.cc
index 1861dbf..8ed7f1f 100644
--- a/src/selfplay/game.cc
+++ b/src/selfplay/game.cc
@@ -53,11 +53,10 @@ const OptionId kMinimumAllowedVistsId{
     "Unless the selected move is the best move, temperature based selection "
     "will be retried until visits of selected move is greater than or equal to "
     "this threshold."};
-}  // namespace
-
-const OptionId SelfPlayGame::kUciChess960{
+const OptionId kUciChess960{
     "chess960", "UCI_Chess960",
     "Castling moves are encoded as \"king takes rook\"."};
+}  // namespace
 
 void SelfPlayGame::PopulateUciParams(OptionsParser* options) {
   options->Add<BoolOption>(kReuseTreeId) = false;
@@ -72,6 +71,8 @@ void SelfPlayGame::PopulateUciParams(OptionsParser* options) {
 SelfPlayGame::SelfPlayGame(PlayerOptions player1, PlayerOptions player2,
                            bool shared_tree, const MoveList& opening)
     : options_{player1, player2} {
+  chess960_ = player1.uci_options->Get<bool>(kUciChess960.GetId()) |
+              player2.uci_options->Get<bool>(kUciChess960.GetId());
   tree_[0] = std::make_shared<NodeTree>();
   tree_[0]->ResetToPosition(ChessBoard::kStartposFen, {});
 
@@ -114,7 +115,7 @@ void SelfPlayGame::Play(int white_threads, int black_threads, bool training,
           std::make_unique<CallbackUciResponder>(
               options_[idx].best_move_callback, options_[idx].info_callback);
 
-      if (!options_[idx].uci_options->Get<bool>(kUciChess960.GetId())) {
+      if (!chess960_) {
         // Remap FRC castling to legacy castling.
         responder = std::make_unique<Chess960Transformer>(
             std::move(responder), tree_[idx]->HeadPosition().GetBoard());
@@ -205,8 +206,7 @@ void SelfPlayGame::Play(int white_threads, int black_threads, bool training,
                                          kMinimumAllowedVistsId.GetId())) {
         break;
       }
-      auto move_list_to_discard =
-          GetMoves(!options_[idx].uci_options->Get<bool>(kUciChess960.GetId()));
+      auto move_list_to_discard = GetMoves();
       move_list_to_discard.push_back(move);
       options_[idx].discarded_callback(move_list_to_discard);
       search_->ResetBestMove();
@@ -218,7 +218,7 @@ void SelfPlayGame::Play(int white_threads, int black_threads, bool training,
   }
 }
 
-std::vector<Move> SelfPlayGame::GetMoves(bool legacy) const {
+std::vector<Move> SelfPlayGame::GetMoves() const {
   std::vector<Move> moves;
   for (Node* node = tree_[0]->GetCurrentHead();
        node != tree_[0]->GetGameBeginNode(); node = node->GetParent()) {
@@ -229,7 +229,7 @@ std::vector<Move> SelfPlayGame::GetMoves(bool legacy) const {
   while (!moves.empty()) {
     Move move = moves.back();
     moves.pop_back();
-    if (legacy) move = pos.GetBoard().GetLegacyMove(move);
+    if (!chess960_) move = pos.GetBoard().GetLegacyMove(move);
     pos = Position(pos, move);
     // Position already flipped, therefore flip the move if white to move.
     if (!pos.IsBlackToMove()) move.Mirror();
diff --git a/src/selfplay/game.h b/src/selfplay/game.h
index 26626e2..93d9a01 100644
--- a/src/selfplay/game.h
+++ b/src/selfplay/game.h
@@ -87,15 +87,13 @@ class SelfPlayGame {
   void WriteTrainingData(TrainingDataWriter* writer) const;
 
   GameResult GetGameResult() const { return game_result_; }
-  std::vector<Move> GetMoves(bool legacy) const;
+  std::vector<Move> GetMoves() const;
   // Gets the eval which required the biggest swing up to get the final outcome.
   // Eval is the expected outcome in the range 0<->1.
   float GetWorstEvalForWinnerOrDraw() const;
   int move_count_ = 0;
   uint64_t nodes_total_ = 0;
 
-  static const OptionId kUciChess960;
-
  private:
   // options_[0] is for white player, [1] for black.
   PlayerOptions options_[2];
@@ -114,6 +112,7 @@ class SelfPlayGame {
   // Track the maximum eval for white win, draw, black win for comparison to
   // actual outcome.
   float max_eval_[3] = {0.0f, 0.0f, 0.0f};
+  bool chess960_;
   std::mutex mutex_;
 
   // Training data to send.
diff --git a/src/selfplay/tournament.cc b/src/selfplay/tournament.cc
index 352e130..5738938 100644
--- a/src/selfplay/tournament.cc
+++ b/src/selfplay/tournament.cc
@@ -283,8 +283,7 @@ void SelfPlayTournament::PlayOneGame(int game_number) {
     game_info.game_result = game.GetGameResult();
     game_info.is_black = player1_black;
     game_info.game_id = game_number;
-    game_info.moves = game.GetMoves(
-        !options[0].uci_options->Get<bool>(SelfPlayGame::kUciChess960.GetId()));
+    game_info.moves = game.GetMoves();
     game_info.play_start_ply = opening.size();
     if (!enable_resign) {
       game_info.min_false_positive_threshold =
```

**Comment by Mardak** [comment]
Is the concern to avoid having player1 vs player2 chess960 flags? If so, maybe `SelfPlayTournament` could have a single flag to pass in to `SelfPlayGame` constructor? And down the line, instead of passing in a flag, `chess960_` could be determined by the starting position vs x-fen.

**Comment by mooskagh** [comment]
Regarding borg@'s suggestion, I like it, will apply today in the evening.
For separate player1/player2 flags, I think it's fine, we already have a few flags like that. We can do something like `player1.uci_options->GetParent()...` then per-player options will be ignored. Correct solution would be to disable using `--player1.chess960` for arguments like that, but I think it's better not to delay v0.23 because of that.

**Comment by mooskagh** [comment]
I prefer flag to startpos detection because classical startpos is actually also FRC position and it may bring some surprises to a client code (not only our client.exe but other people using selfplay for their reasons).

**Comment by borg323** [comment]
Note that my patch does or the two player flags, so setting either one is enough:
```diff
+  chess960_ = player1.uci_options->Get<bool>(kUciChess960.GetId()) |
+              player2.uci_options->Get<bool>(kUciChess960.GetId());
```
There is another instance where we should handle a difference in the player options (but we ignore it):
```c++
  // TODO: This assumes both players have the same resign style.
  // Supporting otherwise involves mixing the meaning of worst.
  if (options_[0].uci_options->Get<bool>(kResignWDLStyleId.GetId()))...
```

**Pull request merged**
