### PR TITLE
remove selfplay interactive mode

### PR DESCRIPTION
**Pull request by borg323**
I don't think anyone is using this any more.

### CODE REVIEW

**Comment by ValZapod** [comment]
I use it ;)

**Comment by borg323** [comment]
@ValZapod can you share some details about how you use it, and if there is anything we can add to improve it?

**Comment by Naphthalin** [comment]
There wasn't any follow-up, so the clean-up can likely be done.

**Comment by borg323** [comment]
Since there is at least one user I don't see the reason to merge it.

**Pull request closed without merging**
