### PR TITLE
Quick patch for negative gamma

### PR DESCRIPTION
**Pull request by Ttl**
Still wrong, but at least it's consistently wrong. Fixes at least some of the T40 problems.

### CODE REVIEW

**Comment by killerducky** [comment]
Just adding some notes from @Mardak test. Following position is lost for black. But `Q=0.35` without fix says black is winning. `Q=-0.95` with fix correctly says we're losing. Note `P` value changed also.

https://lichess.org/tZIu3CMS#137

```
position startpos moves e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 b8c6 g1f3 c8d7 f1e2 g8e7 e1g1 a8c8 d4c5 e7g6 c1e3 c6e5 f3e5 g6e5 b1a3 a7a6 f2f4 e5c6 a3c2 g7g6 b2b4 f8g7 d1d2 e8g8 a2a4 f8e8 c2d4 c6e7 e2d1 c8b8 d4f3 d8c7 g2g4 e7c6 d1b3 b8d8 a1e1 d7c8 h2h3 c7d7 e1d1 d7c7 g1g2 h7h6 e3f2 c8d7 f2g3 c7c8 g2g1 c8c7 g1h2 c7c8 g3h4 c6e7 f3e5 c8c7 h4g3 d7c8 e5f3 c7d7 b3c2 e8f8 d2d3 e7c6 h2g2 d8e8 f3e5 c6e5 f4e5 d7c7 d1e1 c7e7 h3h4 c8d7 h4h5 e7g5 g2h3 f7f5 e5f6 g7f6 d3g6 g5g6 c2g6 f6c3 g6e8 f8e8 e1c1 c3g7 b4b5 a6b5 c1b1 b5b4 b1b4 d7c6 g4g5 h6g5 b4g4 e8f8 f1f8 g8f8 g4g5 g7f6 g5g4 f8f7 a4a5 d5d4 g3h4 f6e5 h4g5 d4d3 g5d2 c6f3 g4b4 f7g8 b4b3 f3e4 h3g4 e5d4 g4f4 e4d5 b3d3 d4c5 f4e5 g8h7 d3c3 c5f8 h5h6 h7g6 c3c8 f8h6 d2h6
go nodes 2 searchmoves g6h6

41300 current: g6h6  (612 ) N:       1 (+ 0) (P: 24.25%) (Q:  0.35175) (D:  0.000) (U: 0.36376) (Q+U:  0.71552) (V:  0.3518) 
41300 with fix: g6g6  (612 ) N:       1 (+ 0) (P: 39.90%) (Q: -0.94676) (D:  0.000) (U: 0.59861) (Q+U: -0.34814) (V: -0.9468) 
```

**Comment by Mardak** [comment]
Here's rerunning the 7piece value test with the `abs(s)` change on networks 41250-41300 by 10s:
screen shot 2019-03-04 at 9 56 41 am

**Comment by killerducky** [comment]
Also Ttl's test posted to discord:

```
Before:
Score of lc0_41306 vs lc0_41312: 9 - 0 - 2  [0.909] 11

After:
Score of lc0_41306 vs lc0_41312: 6 - 5 - 17  [0.518] 28
```

**Comment by Mardak** [comment]
Here's rerunning the 7piece value test with the `abs(s)` change on networks various networks from 41000 to 41306:

screen shot 2019-03-04 at 10 44 44 am

Looks like 41000 41200 41230 41240 41250 41270 41290 41306 (last one notably is filling up the training window right now) are unaffected by the bug. The rerun networks show no spikes (where red spikes indicate many losing positions evaluating as winning)

And some more networks for the position from the earlier comment https://github.com/LeelaChessZero/lc0/pull/778#issuecomment-469351913:
```
position startpos moves e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 b8c6 g1f3 c8d7 f1e2 g8e7 e1g1 a8c8 d4c5 e7g6 c1e3 c6e5 f3e5 g6e5 b1a3 a7a6 f2f4 e5c6 a3c2 g7g6 b2b4 f8g7 d1d2 e8g8 a2a4 f8e8 c2d4 c6e7 e2d1 c8b8 d4f3 d8c7 g2g4 e7c6 d1b3 b8d8 a1e1 d7c8 h2h3 c7d7 e1d1 d7c7 g1g2 h7h6 e3f2 c8d7 f2g3 c7c8 g2g1 c8c7 g1h2 c7c8 g3h4 c6e7 f3e5 c8c7 h4g3 d7c8 e5f3 c7d7 b3c2 e8f8 d2d3 e7c6 h2g2 d8e8 f3e5 c6e5 f4e5 d7c7 d1e1 c7e7 h3h4 c8d7 h4h5 e7g5 g2h3 f7f5 e5f6 g7f6 d3g6 g5g6 c2g6 f6c3 g6e8 f8e8 e1c1 c3g7 b4b5 a6b5 c1b1 b5b4 b1b4 d7c6 g4g5 h6g5 b4g4 e8f8 f1f8 g8f8 g4g5 g7f6 g5g4 f8f7 a4a5 d5d4 g3h4 f6e5 h4g5 d4d3 g5d2 c6f3 g4b4 f7g8 b4b3 f3e4 h3g4 e5d4 g4f4 e4d5 b3d3 d4c5 f4e5 g8h7 d3c3 c5f8 h5h6 h7g6 c3c8 f8h6 d2h6
go nodes 2 searchmoves g6h6

41000: g6h6  (612 ) N:       1 (+ 0) (P: 36.43%) (Q: -0.94048)
41100: g6h6  (612 ) N:       1 (+ 0) (P: 20.70%) (Q:  0.38734) ***
41200: g6h6  (612 ) N:       1 (+ 0) (P: 39.92%) (Q: -0.96020)
41300: g6h6  (612 ) N:       1 (+ 0) (P: 24.25%) (Q:  0.35175) ***

with your abs(s) PR:
41000: g6h6  (612 ) N:       1 (+ 0) (P: 36.43%) (Q: -0.94048)
41100: g6h6  (612 ) N:       1 (+ 0) (P: 37.63%) (Q: -0.94928) ***
41200: g6h6  (612 ) N:       1 (+ 0) (P: 39.92%) (Q: -0.96020)
41300: g6h6  (612 ) N:       1 (+ 0) (P: 39.90%) (Q: -0.94676) ***
```

**Pull request closed without merging**
