### PR TITLE
U+Q softmax sampled visits

### PR DESCRIPTION
**Pull request by mooskagh**

### CODE REVIEW

**Comment by zz4032** [comment]
Tuning latest code at long TC (50K nodes on opening moves) vs. Stockfish resulted in VisitSoftmax=0.00863.
On very short TC the parameter had no effect. Plausible?
Starting a selfplay match next. Games take very long, so it'll take a while.

**Comment by zz4032** [comment]
lc0-tuned with VisitSoftmax=0.003 vs. lc0
```
Score of lc0-tuned vs lc0: 10 - 23 - 87  [0.446] 120
Elo difference: -37.8 +/- 32.3, LOS: 1.2 %, DrawRatio: 72.5 %
```
Trying VisitSoftmax=0.001 next...

**Comment by zz4032** [comment]
lc0-0.001 with VisitSoftmax=0.001 vs. lc0 (VisitSoftmax=0.0)
```
Score of lc0-0.001 vs lc0: 15 - 51 - 104  [0.394] 170
Elo difference: -74.7 +/- 32.1, LOS: 0.0 %, DrawRatio: 61.2 %
```
Less drawish book was used, therefore Elo difference not comparable to previous matches. But 0.001 still very likely weaker.

**Comment by mooskagh** [comment]
That was an attempt to make multipv more useful, but it probably has to be done otherwise (only change visit decision at root).

**Pull request closed without merging**
