### PR TITLE
Calculate limits for tb hits differently to collisions.

### PR DESCRIPTION
**Pull request by Tilps**
To fix Issue #627 maybe.

The new code as it currently stand contains a huge mess of assumptions that are probably wrong.  I'm doing some quick Elo testing to see how badly wrong they are....

### CODE REVIEW

**Comment by Tilps** [comment]
I could make it less conservative if there are any noticeable regressions, but the logic will get a lot more complicated.

**Comment by Tilps** [comment]
5second + 0.1 run shows possible regression but within error bars.
Score of lc0 dev local build vs lc0 PR619: 26 - 35 - 139 [0.477]
Elo difference: -15.65 +/- 26.57

**Comment by mooskagh** [comment]
The current terminal multivisits are clearly broken, but I'm a bit hesitant to grow `Node` structure even more.

And probably we should have this fixed before TCEC superfinal. Maybe just disable multivisits for terminal nodes (and keep them only for collisions)?..

**Comment by killerducky** [comment]
@Tilps do we need this now the #683 is in?

**Comment by Tilps** [comment]
No need to keep it open - Can ressurrect the logic in future if desired.

**Pull request closed without merging**
