### PR TITLE
minimize max fastmath error considering float32 accuracy

### PR DESCRIPTION
**Pull request by borg323**
The initial fastmath.h functions were optimized analytically to minimize rms error over the full mantissa range. Unfortunately, this was not taking into account the limited float32 accuracy, resulting in a small offset from the desired values. Here I used a numerical optimization approach to tune the constants for minimal error over the full mantissa range, and took the opportunity to minimize max error instead of rms error.

Also improved the comments a bit.

### CODE REVIEW

**Comment by oscardssmith** [comment]
How much better is the new accuracy?

**Comment by borg323** [comment]
Not a lot, max relative error e.g for log2 was 6.65e-3, with this it is 5.23e-3. However the accuracy was not the motivation here, but to eliminate the small offset: FastLog2(1) would return 7.63e-6 instead of 0 (which was a design objective for the approximation).

**Comment by borg323** [comment]
Due to rounding in an intermediate calculation, `FastLog2()` was not monotonic. The latest commit uses an earlier version that doesn't have this problem. This one was slightly slower with some compilers, but after recent changes I expect the difference to be in the noise.

**Comment by borg323** [comment]
After extensive discussion with @ddobbelaere we concluded that minimizing the absolute error is a better objective for `FastLog2()`.

Absolute error plot for latest (blue) and master (red) versions of `FastLog2()`:
absolute3

Relative error plot for latest (blue) and master (red) versions of `FastPow2()`:
relative3

**Comment by jjoshua2** [comment]
How much different would it be if you optimized it for fp16? Pretty much all tournaments use this instead. It's probably not worth keeping two separate fastLog implementations around though?

**Comment by ddobbelaere** [comment]
Here's a benchmark over 10 runs using the script https://github.com/ddobbelaere/tools/blob/master/lc0/benchmark.py

```
# master 06748a4
min       227501
max       231164
stddev    1115
mean      229461
95% CI    ±691

# PR 917
min       227040
max       230418
stddev    1024
mean      228393
95% CI    ±635
```

Slightly slower, but still not within confidence bounds for the given number of runs.

@jjoshua2 The fastmath routines are only exclusively on CPU, where typically `float` has 32 bits precision.

**Comment by borg323** [comment]
This is only used on the cpu side. Even if a cuda version would improve performance, the only exp calls there are for floats.

**Comment by borg323** [comment]
With the above script and `--smart-pruning-factor=0 --movetime=-1 --nodes=1000000 --backend=random --threads=1` I get:
```
#master 06748a4
min       194346 nps
max       195105 nps
stddev    241 nps
mean      194722 nps
95% CI    ±150 nps

#pr917
min       194121 nps
max       196140 nps
stddev    552 nps
mean      195644 nps
95% CI    ±342 nps
```

So in my case 917 is slightly faster, probably the result is compiler dependent. This is with gcc 8.3.0.

**Comment by ddobbelaere** [comment]
Forgot to mention that I used gcc 9.1.1 on Fedora with lto enabled and pext
enabled (but no fast math enabled). The benchmark command was using random
backend with no other flags set (so all default).

Op do 8 aug. 2019 17:58 schreef borg323 <notifications@github.com>:

**Pull request merged**
