### PR TITLE
Add searchmoves functionality

### PR DESCRIPTION
**Pull request by SashaMN**
Example: `go infinite searchmoves a2a3 b2b3`

### CODE REVIEW

**Comment by SashaMN** [comment]
Or, I forgot to filter nodes when output best move

**Comment by mooskagh** [comment]
Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---

*[src/engine.cc, line 91 at r1](https://reviewable.io/reviews/leelachesszero/lc0/40#-LEGU4LzA6GdyH_qnO8A:-LEGU4LzA6GdyH_qnO8B:b-8w13p5) ([raw file](https://github.com/leelachesszero/lc0/blob/6b350b6ff0409d90a3f84542668df43fc44d2b66/src/engine.cc#L91)):*
> ```cpp
>     for (const auto& move : params.searchmoves) {
>       limits.searchmoves.emplace_back(move, flip);
>       flip = !flip;
> ```

I don't get it. What does searchmoves mean?

Here you flip it like it's a list of consecutive moves (white, then black, then white),
and in search.cc you filter them all at the same root level.

---


*Comments from [Reviewable](https://reviewable.io/reviews/leelachesszero/lc0/40)*

**Comment by SashaMN** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/engine.cc, line 91 at r1](https://reviewable.io/reviews/leelachesszero/lc0/40#-LEGU4LzA6GdyH_qnO8A:-LEGVkYWBHdahTCo7bhN:bg9jtdd) ([raw file](https://github.com/leelachesszero/lc0/blob/6b350b6ff0409d90a3f84542668df43fc44d2b66/src/engine.cc#L91)):*
<details><summary><i>Previously, mooskagh (Alexander Lyashuk) wrote…</i></summary><blockquote>

I don't get it. What does searchmoves mean?

Here you flip it like it's a list of consecutive moves (white, then black, then white),
and in search.cc you filter them all at the same root level.
</blockquote></details>

You are right, doing a stupid thing here. Fixed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/leelachesszero/lc0/40)*

**Comment by mooskagh** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/leelachesszero/lc0/40#-:-LEM2GxB1EZoscXi4inD:bnfp4nl)*

**Pull request merged**
