### PR TITLE
reset timer only on go command, not position

### PR DESCRIPTION
**Pull request by wakamex**
may help with the insta-moves we're seeing at CCC. will run a test.

### CODE REVIEW

**Comment by wakamex** [comment]
fixes the insta-move in my tested case (CCC settings, 4x2080ti)
```
[ repeating from beginning with PR ]
position startpos moves e2e4 e7e6 d2d4 d7d5 b1c3 g8f6
go wtime 8929000 btime 8929000 winc 5000 binc 5000
[ move in 82 seconds. tree grows from 4.3 million to 5.8 million. ]
info depth 27 seldepth 81 time 82481 nodes 5808514 score cp 43 wdl 308 533 159 nps 24041 tbhits 0 pv e4e5 f6d7 f2f4 c7c5 g1f3...
```

before this change
```
uci
isready
position startpos moves e2e4 e7e6
go wtime 9000000 btime 9000000 winc 5000 binc 5000
[ takes me 86-89 seconds ]
position startpos moves e2e4 e7e6 d2d4 d7d5
go wtime 8924000 btime 8924000 winc 5000 binc 5000
[ takes me 72-74 seconds ]
position startpos moves e2e4 e7e6 d2d4 d7d5 b1c3 g8f6
[wait 75 seconds SF took to make 3.. Nf6 ]
go wtime 8929000 btime 8929000 winc 5000 binc 5000
[ move in 0.2 seconds. tree cut from 4.1 million to 3.6 million. watch nps in evals go from 58k to 15k 1 eval later then 12k ]
info depth 22 seldepth 37 time 74823 nodes 3644707 score cp 44 wdl 317 518 165 nps 58181 tbhits 0 pv e4e5 f6d7 f2f4 c7c5 g1f3...
info depth 23 seldepth 37 time 74868 nodes 3644889 score cp 44 wdl 317 518 165 nps 14678 tbhits 0 pv e4e5 f6d7 f2f4 c7c5 g1f3...
info depth 24 seldepth 69 time 74946 nodes 3645684 score cp 44 wdl 317 518 165 nps 12067 tbhits 0 pv e4e5 f6d7 f2f4 c7c5 g1f3...
info depth 23 seldepth 69 time 74952 nodes 3645844 score cp 44 wdl 317 518 165 nps 12692 tbhits 0 pv e4e5 f6d7 f2f4 c7c5 g1f3...
info depth 23 seldepth 69 time 75022 nodes 3646675 score cp 44 wdl 317 518 165 nps 12419 tbhits 0 pv e4e5 f6d7 f2f4 c7c5 g1f3...
bestmove e4e5 ponder f6d7

[ repeat and do these back-to-back. copy and paste them together, including newline ]
position startpos moves e2e4 e7e6 d2d4 d7d5 b1c3 g8f6
go wtime 8929000 btime 8929000 winc 5000 binc 5000
[ move in 129 seconds. tree regrows from 3.6 million to 6.6 million. ]
info depth 30 seldepth 84 time 129310 nodes 6629802 score cp 43 wdl 304 540 156 nps 23086 tbhits 0 pv e4e5 f6d7 f2f4 c7c5 g1f3...
bestmove e4e5 ponder f6d7

[ repeating test from beginning without the delay. ]
position startpos moves e2e4 e7e6 d2d4 d7d5 b1c3 g8f6
go wtime 8929000 btime 8929000 winc 5000 binc 5000
[ move in 96 seconds. tree grows from 3.5 million to 6.0 million. ]
info depth 24 seldepth 82 time 95929 nodes 6046748 score cp 44 wdl 309 531 160 nps 26320 tbhits 0 pv e4e5 f6d7 f2f4 c7c5 g1f3...
bestmove e4e5 ponder f6d7
```

**Comment by Tilps** [comment]
Unfortunately the current behavior here is WAI.  If this fixes instamoving, then PR1080 should also fix instamoving, but without also increasing risk of being flagged by UCI hosts that are extra picky about how they do their timing.
Can you validate PR1080 for me?

**Comment by wakamex** [comment]
didn't expect it to make a difference at 30s+0.5s against itself, where very similar move timing between variants of the same engine, plus little variability in time spent on each move (in absolute terms, looked like 0.3-1.5s) should mean little risk of insta-moving, and little impact of it does happen? but seems like there is some. could be bigger at long TC. or if a UCI host leaves pausing between "position" and "go" commands, which I'm pretty sure CCC is doing. will rerun with PR 1080.
```
TC = 30s + 0.5s openings-6ply-1000.pgn against CCC settings on 4x2080ti
   # PLAYER      :  RATING  ERROR  POINTS  PLAYED   (%)  CFS(%)    W    D    L  D(%)
   1 PR1081      :     9.2   11.3    99.0     193  51.3      95    8  182    3  94.3
   2 4xgpuCCC    :     0.0   ----    94.0     193  48.7     ---    3  182    8  94.3

White advantage = 20.06 +/- 5.85
Draw rate (equal opponents) = 100.00 % +/- 0.21

"N","NAME",0,1
0,"               PR1081",,94.6
1,"             4xgpuCCC",5.4,
```

**Comment by mooskagh** [comment]
Cutechess starts move timer on `position`, not `go`. I don't think it's correct, but that's what it does, that's why we also have to. (they used to, I heard that's fixed now?)

Arena is not any better, it sends `position`, `isready` and `go` together, not waiting for `readyok` in response to `isready` at all. If we are for some reason slow to prepare the search, we time out.

As those two most popular GUIs do that, there's nothing else we can do other than also start timer.

See e.g. https://github.com/LeelaChessZero/lc0/pull/427

**Comment by wakamex** [comment]
turns out performance is unchanged, as expected.
```   # PLAYER      :  RATING  ERROR  POINTS  PLAYED   (%)  CFS(%)    W    D    L  D(%)
   1 PR1081      :     0.9    8.5   203.5     406  50.1      58   14  379   13  93.3
   2 4xgpuCCC    :     0.0   ----   202.5     406  49.9     ---   13  379   14  93.3

White advantage = 23.34 +/- 4.36
Draw rate (equal opponents) = 100.00 % +/- 0.23

"N","NAME",0,1
0,"               PR1081",,57.9
1,"             4xgpuCCC",42.1,
```

**Pull request closed without merging**
