### PR TITLE
Don't do any smart pruning if smart pruning factor is 0 or lower.

### PR DESCRIPTION
**Pull request by Tilps**
Also disable this smart pruning in benchmark and selfplay that don't support self pruning setting.

### CODE REVIEW

**Comment by Tilps** [comment]
This logic change reverts behavior to before PR884, where playouts_remaining_ was never set if smart pruning factor was <=0

**Comment by Tilps** [comment]
Hopefully fixes #1306 when smart pruning is disabled.

**Comment by jkormu** [comment]
Seems to fix the issue in #1306 regarding position 8/5pp1/3k2p1/1p6/pPB5/P4Kb1/5PP1/8 w - - 0 1, where a move jumps from 0 to hero when go node limit is increased just by 1 node.

**Comment by mooskagh** [comment]
Hmm it feels like instead of passing that to stoppers, it's cleaner to somehow either ignore it in search or maybe unset in the last stopper in chain..
Because logically it's just telling how many nodes are left, and it's up to search to decide what to do with that information.
I'll look more tomorrow morning.

**Comment by Tilps** [comment]
my first thought was to add it to the if statement in search - but since smart pruning factor is a 'stopper parameter' now and no longer part of params.cc - this seemed much simpler :P

In some sense I actually like this way better - because playouts remaining estimate is already not updated based on time control and nps estimate if smart pruning factor is 0 - so this just makes it consistently not updated rather than inconsistently not updated. At least when its consistently not updated its clearer that it isn't usable outside of a smart pruning scenario.

**Comment by mooskagh** [comment]
Ok, then probably it makes sense at least to pass `bool populate_remaining_moves` instead of `float` (as that float is only used to be compared with 0).

**Comment by Tilps** [comment]
Done.

**Comment by Tilps** [comment]
Just realized I used your recommended name without thinking - should be populate_remaining_playouts - will change.

**Pull request merged**
