### PR TITLE
update or clone submodule if not there

### LINKED ISSUE #554: meson.build:66:0: ERROR
Just after running build.sh I got this Error:

_Build started at 2018-12-04T21:36:05.267526
Main binary: /usr/bin/python3
Python system: Linux
The Meson build system
Version: 0.45.1
Source dir: /home/bamdad/Schreibtisch/lc0-master
Build dir: /home/bamdad/Schreibtisch/lc0-master/build/release
Build type: native build
Project name: lc0
Sanity testing C++ compiler: c++
Is cross compiler: False.
Sanity check compiler command line: c++ /home/bamdad/Schreibtisch/lc0-master/build/release/meson-private/sanitycheckcpp.cc -o /home/bamdad/Schreibtisch/lc0-master/build/release/meson-private/sanitycheckcpp.exe
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /home/bamdad/Schreibtisch/lc0-master/build/release/meson-private/sanitycheckcpp.exe
Native C++ compiler: c++ (gcc 7.3.0 "c++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Library libprotobuf found: YES
Program protoc found: YES (/usr/bin/protoc)

meson.build:66:0: ERROR: File libs/lczero-common/proto/net.proto does not exist._

As I am a total programming noob, I would really apreciate your help ! thx in advance

### PR DESCRIPTION
**Pull request by borg323**
Closes #554

### CODE REVIEW

**Comment by NicolaiHartmann** [comment]
would you please tell me how to do this exactly ?

**Comment by borg323** [comment]
This just makes the error more informative, suggesting to run ` git submodule update --init --recursive --remote`

**Comment by NicolaiHartmann** [comment]
after getting the error and running git submodule update...
I get the following error:

fatal: Kein Git-Repository (oder irgendeines der Elternverzeichnisse): .git
         no Git-Repository (or any of parent directory): .git

And the files for placing the submodule aren't available anymore ?!

**Comment by borg323** [comment]
It seems you downloaded the zip file and didn't clone the git repository. Probably the easier thing to do is download the files from https://github.com/LeelaChessZero/lczero-common and put them in the `libs/lczero-common` directory. If you still have trouble, better ask in the #help channel on [discord](https://discord.gg/pKujYxD)

**Pull request merged**
