### PR TITLE
Efficient and informative depth computation.

### PR DESCRIPTION
**Pull request by Videodr0me**
This computes depth more efficiently and replaces full_depth with the more informative average depth:

1. both max_depth and full_depth are removed from the node structure freeing space
2. the checking of all siblings for full_depth computation is no longer needed
3. full_depth rarely got larger than 5 even on fast machines and long searches
4. average depth replaces full_depth as a more informative measure
5. max_depth reflects search depth not tree depth
6. max_depth is consistent with length of pv displayed (if pv stems from the max depth line)
7. max_depth and cum_depth (for averaging) are computed in a two step process, first per batch and only after the mutexed search->max_depth and search->cum_depth are updated. This is in preparation of a mutex reorg.
8. For discussion: average depth is true average depth and thus can also decrease (informing about leela currently exploring a wider tree). This is rare, my own testing with chessbase gui and cutechess as well as Dubslows testing showed no problems with this. It could easily be modified to be monotonically increasing.

### CODE REVIEW

**Comment by dubslow** [comment]
I don't approve of this for [this](https://github.com/LeelaChessZero/lc0/issues/86#issuecomment-408179482) reason. On TCEC this would engender all sorts of horrifying misconceptions: on one move, when Lc0 makes a new tree with 1M nodes, gets an average depth of (say) 20 and max depth 45, which is well and good; then the next move is one of those 600ms smart pruned moves, will result in a average depth of possibly like 30 and a max depth of 30 as well. So with a 600ms move, average depth will increase by several ply and max depth will decrease by several ply, in a 600ms move. That will cause mass confusion as to how exactly the depth is calculated, and will lead to falsehoods galore being spread as truth because no one knows any better.

**Comment by Videodr0me** [comment]
I am aware of your understanding of what depth should be, which is kind of "unique". SF and other engines have no reproducability of depth due to multi threadedness and using hash info. Selective depth of SF also fluctuates from move to move, especially on hash hits.  "Normal" engines depth output is not clearly defined either, in particular when considering the extensive pruning and extension regimes. Average depth is exactly what it says it is, and thus if only one line is searched, max depth and average depth are naturally identical. The main advantages of this proposal over your previous ones are:
- no full tree traversal
- no wasted space in nodes
- depth is real search depth and not tree depth
- a vote on discord preferred this solution
This is essentially a cosmetic issue having no effect on playing strength and therefore should not lead to needless overcomplication and wasted resources (time or space).

**Comment by dubslow** [comment]
Please do not make references to votes on Discord, especially when I made one that showed that this option was *not* preferred. And the "search" depth is far less important than the move-analysis depth. I cannot speak to other engines, except to say that their analysis is wiped fresh and restarted for each subsequent move, which differs quite dramatically from our tree reuse.

**Comment by Videodr0me** [comment]
Hash is not wiped between moves - some engines do, most don't. I do not share your view on "move-analysis" depth (whatever thats supposed to be) and I think not outputting anything at all would be less informative. However you interpret depth, average depth, max depth, tree depth or "move-analysis depth", calling any of these "lies" is unprofessional and besides the point. All of these are computed from actual search data and the way they are computed is completely transparent and can be verified by looking at the source. 

I played a bit of chess in the day and used engine analysis regularily for opening preparation and game analysis. In my view the only thing which might warrant a discussion is that average depth, both in this and your proposal, can decrease occasionally, which will be of a much bigger surprise to anybody than the cases you find objectionable.

**Comment by dubslow** [comment]
You approve this and merge without so much as a by your leave? Really?

**Comment by dubslow** [comment]
Hash is not anywhere near the same thing as preserving the tree -- the shape of the search may be quite different even as the hash is recycled between moves. This is *not* so for Leela, the old search is reused in exactly the same way as it was made, a sort of checkpoint from which to continue that old search, so the old depth information must be included as well.

These numbers are generated from search data, but as I explained in my comment, the data from one `Search` instantiation does *not* describe the entirety of the move analysis generated by Leela in the case of tree reuse, and presenting depth information from only the most recent `Search`, not from the `NodeTree`, is misleading to the point of being simply wrong, and so it's not a stretch to call it a lie. It is perhaps linguistically hyperbolized, but it is also accurate.

**Comment by cn4750** [comment]
@Videodr0me, I am not sure it will be a large surprise to people if average depth decreases occasionally. Houdini 3 was one of the first popular engines to have decreasing depths in search due to its use of Accelerated Principal Variation Search, a.k.a. smart fail-high. I think most of the popular GUIs fixed any bugs related to decreasing depths as a result of this.

**Comment by Videodr0me** [comment]
@cn4750 Thats good to hear. In my limited testing i also found no issues with chessbase gui and cutechess.

**Pull request merged**
