### PR TITLE
Add fpu type 'prediction' based off ideas in leela-zero PR2342

### PR DESCRIPTION
**Pull request by Tilps**
Untested for now.

### CODE REVIEW

**Comment by Tilps** [comment]
prediction vs reduction at 10 seconds with 0.2 increment for 100 games on my machine (RTX2080TI) was a draw (with 4 wins a piece).  But I presume that the fpu-value should be reduced to maximize results, I left it at the default of 1.2.  And maybe further performance tuning of the erfinv_approx would help.

**Comment by zz4032** [comment]
Test match with tuned parameter values

TC: 2.4s/game+0.01s/move (~900nodes/move)
```
   # PLAYER             :  RATING  ERROR  LOS(%)   GAMES  DRAWS(%)
   1 lc0-tuned          :     0.0   ----    79.7    1000      64.3
   2 lc0_PR835-tuned    :    -5.3   12.4     ---    1000      64.3

White ELO advantage = 7.4
Draw rate (equal opponents) = 64.4 %
```
- lc0_PR835-tuned (FpuStrategy=prediction, FpuValue=1.25, FpuStrategyAtRoot=prediction, FpuValueAtRoot=1.26)
- lc0_tuned (FpuValue=0.84, FpuValueAtRoot=0.24)

**Comment by Tilps** [comment]
re-reading 2342 it looks like leela-zero uses 'original parent Q' for its reduction rather than the dynamic parent q like we do.  As such this change probably should be modified to use the weighted average visited policy, rather than the max policy. I'll do that when I can.

**Comment by Tilps** [comment]
Changed.  I would assume this would push the clop value even higher - although I have to say that the 1.25 value found before already exceeded my expectations greatly.

**Comment by borg323** [comment]
Alternative erfinv_approx suggestion:
sign\*(std::sqrt(-0.614226351693f\*FastLog2((1-x)\*(1+x)))+0.142958311714f\*x\*(x-0.066398217886f)\*(x-1.357506047023f))
image
The absolute error is shown in black, in red is the current version, and in black is the piecewise quadratic mentioned in https://github.com/leela-zero/leela-zero/pull/2342#issuecomment-484122067

**Comment by Tilps** [comment]
Implemented the approximation proposal above.

**Comment by zz4032** [comment]
Match with updated code
Parameters retuned for lc0_PR835-tuned.
TC: 2.4s/game+0.01s/move (~900nodes/move)
```
   # PLAYER             :  RATING  ERROR  LOS(%)   GAMES  DRAWS(%)
   1 lc0-tuned          :     0.0   ----    98.8    1000      63.7
   2 lc0_PR835-tuned    :   -14.4   12.6     ---    1000      63.7

White ELO advantage = 8.1
Draw rate (equal opponents) = 63.9 %
```
- lc0_PR835-tuned (FpuStrategy=prediction, FpuValue=1.10, FpuStrategyAtRoot=prediction, FpuValueAtRoot=1.58)
- lc0_tuned (FpuValue=0.84, FpuValueAtRoot=0.24)

**Comment by Tilps** [comment]
heh getting worse :P hrmm not sure what else to try.

**Comment by zz4032** [comment]
With current Master, LD2 network, more nodes/move and this time tuning and matches are vs. SF.

TC (LC0): 1.98s/game+0.033s/move (~3500 nodes/move with LD2)
MinibatchSize=32
Tuning results:
`lc0-tuned` with FpuStrategy=reduction, FpuStrategyAtRoot=same (default):
CPuct=1.98, FpuValue=0.52 (8000 games vs. SF)
`lc0_PR835-tuned` with FpuStrategy=prediction, FpuStrategyAtRoot=prediction, CPuct fixed at 1.98:
CPuct=1.98, FpuValue=0.58, FpuValueAtRoot=1.93 (10000 games vs. SF)
```   
   # PLAYER             :  RATING  ERROR  CFS(%)   GAMES  DRAWS(%)
   1 lc0_PR835-tuned    :     1.7    7.4    67.3    5000      40.4
   2 stockfish          :     0.0   ----    84.0   10000      40.9
   3 lc0-tuned          :    -3.8    7.5     ---    5000      41.5

White advantage = -0.5 +/- 2.8
Draw rate (equal opponents) = 40.9 % +/- 0.5
```
CFS of `lc0_PR835-tuned` in relation to `lc0-tuned`: 85.0%.

**Comment by Naphthalin** [comment]
Does the reasoning behind https://github.com/leela-zero/leela-zero/issues/2342 actually apply to Lc0 as well?
- LZ has merged a change from parent_original_eval to parent_average_eval by now
- Go has a very high number of (bad) moves, which has a bad interaction with the way LZ has only noise/no PST policy flattening implemented in training
- the desired behavior of this is probably mostly met with an appropriately tuned FPU value already

As this PR didn't show any gains for lc0, the increased complexity isn't worth it, and I recommend closing this PR.

**Comment by Tilps** [comment]
Yeah I gave up on this long ago, good to close.

**Pull request closed without merging**
