### PR TITLE
Try sorting edges to speed up node selecting.

### PR DESCRIPTION
**Pull request by Tilps**
So far, doesn't seem to work... will need to profile.

### CODE REVIEW

**Comment by Naphthalin** [comment]
Any news on this?

**Comment by Tilps** [comment]
I've not had a chance to come back to it - but the idea still has potential.

**Comment by Naphthalin** [comment]
This needs to be carefully looked at again in combination with #1360.

**Comment by Tilps** [comment]
Closing in favor of #1376 .

**Pull request closed without merging**
