### PR TITLE
faster winograd TransformIn

### PR DESCRIPTION
**Pull request by ra1u**
This improves CPU efficiency in TransformIn. Improvement is in cache utilization and  for this particular part of code on larger cache sizes.

More details:
Besides twidling data around TransformIn makes transposion of data.

    memory_read_shape [batch][chan][y][x][16]

if output shape would be such ordering, we would have perfect cache utilization, but output shape is

    memory_out_shape [16][batch][y][x][chan]

Current patch makes signification performance improvement, but cache optimal solution (aka cache-oblivious) remains unsolved puzzle for me.

### CODE REVIEW

**Comment by frpays** [comment]
threads | batch_size | cores | master | cache | ispc | cache speed-up | ispc-speed-up | ispc from cache
-- | -- | -- | -- | -- | -- | -- | -- | --
2 | 4 | 1 | 73 | 79 | 80 | 8% | 10% | 1%
2 | 8 | 1 | 76 | 83 | 84 | 9% | 11% | 1%
2 | 32 | 1 | 75 | 77 | 81 | 3% | 8% | 5%
2 | 512 | 1 | 73 | 73 | 79 | 0% | 8% | 8%
2 | 4 | 2 | 112 | 126 | 129 | 13% | 15% | 3%
2 | 8 | 2 | 117 | 132 | 137 | 13% | 17% | 4%
2 | 32 | 2 | 115 | 129 | 136 | 12% | 18% | 6%
2 | 512 | 2 | 112 | 114 | 133 | 2% | 19% | 17%
2 | 4 | 4 | 162 | 188 | 202 | 16% | 25% | 9%
2 | 8 | 4 | 166 | 188 | 206 | 13% | 24% | 11%
2 | 32 | 4 | 163 | 171 | 198 | 5% | 21% | 17%
2 | 512 | 4 | 154 | 157 | 191 | 2% | 24% | 22%
4 | 4 | 1 | 134 | 142 | 147 | 6% | 10% | 4%
4 | 8 | 1 | 136 | 148 | 153 | 9% | 13% | 4%
4 | 32 | 1 | 139 | 142 | 150 | 2% | 8% | 6%
4 | 512 | 1 | 135 | 136 | 143 | 1% | 6% | 5%
4 | 4 | 2 | 209 | 230 | 244 | 10% | 17% | 7%
4 | 8 | 2 | 217 | 243 | 247 | 12% | 14% | 2%
4 | 32 | 2 | 214 | 224 | 243 | 5% | 14% | 9%
4 | 512 | 2 | 205 | 212 | 230 | 3% | 12% | 9%
4 | 4 | 4 | 186 | 208 | 219 | 12% | 18% | 6%
4 | 8 | 4 | 196 | 212 | 226 | 8% | 15% | 7%
4 | 32 | 4 | 196 | 212 | 233 | 8% | 19% | 11%
4 | 512 | 4 | 186 | 196 | 214 | 5% | 15% | 10%
6 | 4 | 1 | 183 | 198 | 201 | 8% | 10% | 2%
6 | 8 | 1 | 189 | 197 | 205 | 4% | 8% | 4%
6 | 32 | 1 | 192 | 200 | 206 | 4% | 7% | 3%
6 | 512 | 1 | 185 | 197 | 207 | 6% | 12% | 5%
6 | 4 | 2 | 277 | 287 | 314 | 4% | 13% | 10%
6 | 8 | 2 | 283 | 300 | 315 | 6% | 11% | 5%
6 | 32 | 2 | 293 | 306 | 320 | 4% | 9% | 5%
6 | 512 | 2 | 270 | 280 | 297 | 4% | 10% | 6%
6 | 4 | 4 | 180 | 218 | 222 | 21% | 23% | 2%
6 | 8 | 4 | 199 | 218 | 223 | 10% | 12% | 3%
6 | 32 | 4 | 206 | 221 | 240 | 7% | 17% | 9%
6 | 512 | 4 | 197 | 215 | 246 | 9% | 25% | 16%

**Comment by frpays** [comment]
Conclusion is: this version is very well worth to integrate. And the ISPC version also.

**Comment by ra1u** [comment]
@frpays Thank you for tests, I suspect that decrease of performance while number of threads goes up is due to relatively large internal cache size. I would like to see performance result with little smaller `kCacheSize` like 16 or 32 for example.

**Comment by borg323** [comment]
I have an experimental patch to make kCacheSize a backend option, e.g.  `--backend-opts=cache-size=32`: <https://github.com/borg323/lc0/commit/af28a00ad08e9ca693239d424020a195bedfb3dc>.

I saw very stable performance over a wide range of values, with 128 close to optimal, so I was happy with it as a default.

**Comment by ra1u** [comment]
Looking at that test code from @borg it seems that there is subtle issue. 
Jump size at [L171](https://github.com/borg323/lc0/blob/af28a00ad08e9ca693239d424020a195bedfb3dc/src/neural/blas/winograd_convolution3.cc#L171) and following 16 lines is equal to 2nd dimension of R. That is 2nd dimension 512 at [L116](https://github.com/borg323/lc0/blob/af28a00ad08e9ca693239d424020a195bedfb3dc/src/neural/blas/winograd_convolution3.cc#L116) should affect performance. 

Possible fix to get relevant test is to address R having single dimension only.

    float R[16 * 512];
    ...
    R[0*kCacheSize+ch] = T1[0][0] - T1[0][2];
    R[1*kCacheSize+ch] = T1[0][1] + T1[0][2];
    ...
    for (size_t ch = 0; ch < channel_step; ++ch) {
       wTile_V[ch] = R[i*kCacheSize+ch];
    }

**Comment by borg323** [comment]
Originally I used the gcc vla extension, and just defined `float R[16][kCacheSize]`. Since this is just test code and I didn't do extensive performance testing of the final variation, but what I did gave identical performance. That being said, I expect that as long as the second dimension is large enough for each write to go to a different cache line it shouldn't affect performance.

**Pull request merged**
