### PR TITLE
Expreimental support for cuDNN 6

### PR DESCRIPTION
**Pull request by borg323**
With this patch I am able to compile and run lc0 on linux using cuDNN version 6 together with CUDA 9. This can probably be refactored, but I don't know CUDA so at this stage I am interested in comments on code correctness.

### CODE REVIEW

**Comment by mooskagh** [comment]
Why would you want to support cuDNN 6? Are there GPUs that work on 6 but not 7?

**Comment by borg323** [comment]
The cuDNN library is already installed in colab so I expect this would simplify using it. It would require downloading a pre-compiled binary but this is doable. 
I am exploring options at the moment, so I don't think this should be merged, at least not in the current form.

**Comment by borg323** [comment]
Found a better workaround, closing

**Comment by radha** [comment]
@borg323   could you describe the workaround for cudnn < 7.1. I am stuck with cuddn 7.0 for another project.

**Comment by borg323** [comment]
@radha the workaround is for colab which has old nvidia drivers (384.111) - According to https://stackoverflow.com/questions/30820513/what-is-version-of-cuda-for-nvidia-304-125/30820690#30820690 only up to cuda 9.0 is compatible. However cuda installation will try to upgrade several other packages so they need to be held to version 384.111: nvidia-384, nvidia-opencl-icd-384, libcuda1-384, nvidia-384-dev, cuda-drivers

**Pull request closed without merging**
