### PR TITLE
meson, don't link pthread when host is Android.

### PR DESCRIPTION
**Pull request by lealgo**
Android's `libc, bionic`, provide built-in support for `pthreads`, so no additional linking is necessary.

### CODE REVIEW

**Comment by lealgo** [comment]
Provided that #1079 is merged, only two PRs are needed to cross-compile to Android: this one and #1083 .
That is for the Eigen back-end. And of course a cross-file would be needed and the NDK toolchain.

**Comment by borg323** [comment]
Can you try if using `deps += dependency('threads')` works unconditionally on android?

**Comment by lealgo** [comment]
> Can you try if using `deps += dependency('threads')` works unconditionally on android?

It works!

```
Dependency threads found: YES
```

**Comment by borg323** [comment]
Do you think this is a better approach?

**Comment by lealgo** [comment]
> Do you think this is a better approach?

Yours, of course it is. This way the dependency is stated explicitly for all targets. I'll push the commit, let's see if appveyor likes it.

**Comment by borg323** [comment]
Seems to work fine under windows as well.

**Pull request merged**
