### PR TITLE
compile fix for older cuda

### PR DESCRIPTION
**Pull request by borg323**

### CODE REVIEW

**Comment by ankan-ban** [comment]
looks good. Thanks for fixing this!

**Comment by ankan-ban** [comment]
instead of memcpy, you can also do:
alpha = *((half*) &one_h);
beta = *((half*) &zero_h);
but probably memcpy is less confusing. I am ok with either.

**Comment by borg323** [comment]
I'm quite sure the casts violate aliasing rules.

**Comment by ankan-ban** [comment]
maybe std::bit_cast is the most modern way of doing this:
https://en.cppreference.com/w/cpp/numeric/bit_cast

**Comment by borg323** [comment]
Unfortunately it is c++20, so we can't  use it.

**Comment by ankan-ban** [comment]
yeah. I think memcpy is fine. For types of same size, the casting the pointer works but using them is not a good idea in general.

**Pull request merged**
