### PR TITLE
WIP : TensorRT backend

### PR DESCRIPTION
**Pull request by ankan-ban**

### CODE REVIEW

**Comment by Error323** [comment]
Note that this PR should not be merged until:

- trt is supported in circleci
- INT8 is tested properly (I'll update the PR section with results)

I'm not sure howto deal with AppVeyor as TensorRT is _not_ supported on Windows. @borg323 got an idea for that?

**Comment by borg323** [comment]
We don't have to do anything for appveyor, only the cudnn, opencl and blas backends will be built for windows. The trt backend will not be built, like the tensorflow backend isn't built for the time being.

**Comment by ankan-ban** [comment]
With tensorRT 5.0, Windows libraries are now available. The FP32 performance is still bad (less than half of cudnn backend).

FP16 is comparable - significantly faster for small batch sizes, but slightly slower for bigger batches. Here are some raw NN eval benchmarks on RTX 2080Ti:

```
TensorRT:
========
-- minibatch-size of 8
Avg batch size: 7.350000, NN eval time: 0.241410 seconds per 735 evals. NPS: 3044.62

-- minibatch-size of 16
Avg batch size: 15.070000, NN eval time: 0.243011 seconds per 1507 evals. NPS: 6201.37

-- minibatch-size of 32
Avg batch size: 16.150000, NN eval time: 0.247604 seconds per 1615 evals. NPS: 6522.52
Avg batch size: 17.790000, NN eval time: 0.249877 seconds per 1779 evals. NPS: 7119.5
Avg batch size: 20.600000, NN eval time: 0.254397 seconds per 2060 evals. NPS: 8097.58
Avg batch size: 25.510000, NN eval time: 0.264043 seconds per 2551 evals. NPS: 9661.29
Avg batch size: 26.890000, NN eval time: 0.262779 seconds per 2689 evals. NPS: 10232.9
Avg batch size: 30.510000, NN eval time: 0.264292 seconds per 3051 evals. NPS: 11544

-- minibatch-size of 64
Avg batch size: 32.040000, NN eval time: 0.268157 seconds per 3204 evals. NPS: 11948.2
Avg batch size: 40.120000, NN eval time: 0.279921 seconds per 4012 evals. NPS: 14332.6
Avg batch size: 42.750000, NN eval time: 0.283184 seconds per 4275 evals. NPS: 15096.2
Avg batch size: 45.870000, NN eval time: 0.287724 seconds per 4587 evals. NPS: 15942.4
Avg batch size: 50.240000, NN eval time: 0.295339 seconds per 5024 evals. NPS: 17011


-- minibatch-size of 128
Avg batch size: 52.340000, NN eval time: 0.296629 seconds per 5234 evals. NPS: 17644.9
Avg batch size: 56.980000, NN eval time: 0.396650 seconds per 5698 evals. NPS: 14365.3
Avg batch size: 75.620000, NN eval time: 0.453766 seconds per 7562 evals. NPS: 16665
Avg batch size: 92.970000, NN eval time: 0.538231 seconds per 9297 evals. NPS: 17273.3
Avg batch size: 95.210000, NN eval time: 0.540443 seconds per 9521 evals. NPS: 17617


-- minibatch-size of 256
Avg batch size: 124.600000, NN eval time: 0.653882 seconds per 12460 evals. NPS: 19055.4
Avg batch size: 137.930000, NN eval time: 0.705234 seconds per 13793 evals. NPS: 19558.1
Avg batch size: 159.250000, NN eval time: 0.795284 seconds per 15925 evals. NPS: 20024.3
Avg batch size: 174.890000, NN eval time: 0.848998 seconds per 17489 evals. NPS: 20599.6


-- minibatch-size of 512
Avg batch size: 195.550000, NN eval time: 0.946863 seconds per 19555 evals. NPS: 20652.4
Avg batch size: 250.860000, NN eval time: 1.183938 seconds per 25086 evals. NPS: 21188.6
Avg batch size: 271.070000, NN eval time: 1.269543 seconds per 27107 evals. NPS: 21351.8


-- minibatch-size of 1024
Avg batch size: 289.960000, NN eval time: 1.345226 seconds per 28996 evals. NPS: 21554.7
Avg batch size: 316.830000, NN eval time: 1.486015 seconds per 31683 evals. NPS: 21320.8
Avg batch size: 337.070000, NN eval time: 1.514362 seconds per 33707 evals. NPS: 22258.2
Avg batch size: 376.680000, NN eval time: 1.675517 seconds per 37668 evals. NPS: 22481.4



cudnn-fp16
=======
-- minibatch-size of 8
Avg batch size: 7.380000, NN eval time: 0.407137 seconds per 738 evals. NPS: 1812.66
Avg batch size: 8.230000, NN eval time: 0.398642 seconds per 823 evals. NPS: 2064.51

-- minibatch-size of 16
Avg batch size: 9.600000, NN eval time: 0.401575 seconds per 960 evals. NPS: 2390.59
Avg batch size: 13.210000, NN eval time: 0.400768 seconds per 1321 evals. NPS: 3296.17
Avg batch size: 14.000000, NN eval time: 0.399129 seconds per 1400 evals. NPS: 3507.64

-- minibatch-size of 32
Avg batch size: 20.650000, NN eval time: 0.400707 seconds per 2065 evals. NPS: 5153.39
Avg batch size: 24.690000, NN eval time: 0.397651 seconds per 2469 evals. NPS: 6208.97
Avg batch size: 26.980000, NN eval time: 0.420835 seconds per 2698 evals. NPS: 6411.06

-- minibatch-size of 64
Avg batch size: 32.080000, NN eval time: 0.411638 seconds per 3208 evals. NPS: 7793.25
Avg batch size: 40.170000, NN eval time: 0.412248 seconds per 4017 evals. NPS: 9744.13
Avg batch size: 45.890000, NN eval time: 0.417293 seconds per 4589 evals. NPS: 10997.1
Avg batch size: 50.420000, NN eval time: 0.417088 seconds per 5042 evals. NPS: 12088.6

-- minibatch-size of 128
Avg batch size: 60.830000, NN eval time: 0.436222 seconds per 6083 evals. NPS: 13944.7
Avg batch size: 72.850000, NN eval time: 0.446055 seconds per 7285 evals. NPS: 16332.1
Avg batch size: 85.250000, NN eval time: 0.467104 seconds per 8525 evals. NPS: 18250.8
Avg batch size: 86.920000, NN eval time: 0.472518 seconds per 8692 evals. NPS: 18395.1
Avg batch size: 98.500000, NN eval time: 0.488477 seconds per 9850 evals. NPS: 20164.7

-- minibatch-size of 256
Avg batch size: 129.580000, NN eval time: 0.654890 seconds per 12958 evals. NPS: 19786.5
Avg batch size: 148.400000, NN eval time: 0.740685 seconds per 14840 evals. NPS: 20035.5
Avg batch size: 176.960000, NN eval time: 0.870070 seconds per 17696 evals. NPS: 20338.6
Avg batch size: 195.080000, NN eval time: 0.924653 seconds per 19508 evals. NPS: 21097.6

-- minibatch-size of 512
Avg batch size: 251.030000, NN eval time: 1.082053 seconds per 25103 evals. NPS: 23199.4
Avg batch size: 325.450000, NN eval time: 1.338939 seconds per 32545 evals. NPS: 24306.6
Avg batch size: 361.660000, NN eval time: 1.436829 seconds per 36166 evals. NPS: 25170.7


```

**Comment by borg323** [comment]
I tried to make appveyor builds for this a few weeks ago but couldn't find a redstributable package like for cudnn.

**Pull request closed without merging**
