### PR TITLE
Value only mode for uci.

### PR DESCRIPTION
**Pull request by Tilps**
This is quick and dirty...

I had intended to share code with multigame.cc - but that would need more refactoring than I originally planned - so for now I have not done so...

### CODE REVIEW

**Comment by Tilps** [comment]
Note that only engine.cc is changed in this PR - the rest is from PR1966.

**Comment by Tilps** [comment]
now just one file to review (since the other PR has been merged)

**Comment by borg323** [comment]
What about adding something like https://github.com/borg323/lc0/commit/709571c85774f97ab504effe65f8544be6f2c9cb for minibatch-size support?

**Comment by Tilps** [comment]
Seems reasonable, do you want to add it to my branch directly rather than have me copy it over?

**Pull request merged**
