### PR TITLE
change q from float to double for averaging reasons

### PR DESCRIPTION
**Pull request by MelleKoning**
#875 
This PR is for changing Q from float to double, to try out if this makes for different (better?) gameplay.

Have a beautiful testset of two games reversed 👍  whereby Qdouble wins as white while it holds the draw as black against Q-float.
Game settings 5 sec for the game +5sec for each move.

```
[Event "My Tournament"]
[Site "HaceTourney"]
[Date "2019.06.07"]
[Round "1"]
[White "lc0.Net.42475"]
[Black "lc0.Net.42475-Qdouble"]
[Result "1/2-1/2"]
[ECO "A00"]
[Opening "Mieses Opening"]
[PlyCount "132"]
[Termination "adjudication"]
[TimeControl "5+5"]

1. d3 {book} g6 {book} 2. c3 {book} d6 {book} 3. e4 {+0.07/6 4.0s}
Nf6 {+0.04/6 3.4s} 4. g3 {+0.04/7 4.5s} Bg7 {+0.03/7 4.2s} 5. Bg2 {+0.02/7 4.1s}
O-O {+0.03/7 4.9s} 6. Ne2 {+0.05/7 4.5s} e5 {0.00/7 4.9s} 7. c4 {+0.08/8 7.5s}
c5 {+0.01/7 5.3s} 8. Nbc3 {+0.03/7 4.8s} Nc6 {+0.02/7 5.9s}
9. O-O {+0.04/7 3.4s} a6 {0.00/7 5.7s} 10. Nd5 {+0.10/7 6.5s} Nxd5 {0.00/8 3.7s}
11. cxd5 {+0.07/8 2.4s} Nd4 {-0.03/8 3.8s} 12. Nxd4 {+0.12/8 3.6s}
exd4 {-0.05/7 3.4s} 13. Bf4 {+0.09/7 9.2s} f5 {-0.03/7 8.0s}
14. Qd2 {+0.15/7 2.8s} fxe4 {-0.06/8 4.0s} 15. Bxe4 {+0.14/7 3.0s}
Bh3 {-0.04/8 6.6s} 16. Rfe1 {+0.14/7 4.3s} b5 {-0.03/8 2.3s}
17. a4 {+0.06/8 7.6s} c4 {+0.04/9 5.7s} 18. axb5 {+0.01/10 3.9s}
c3 {-0.05/11 2.9s} 19. bxc3 {+0.34/11 4.3s} dxc3 {-0.19/10 3.3s}
20. Qe3 {+0.44/12 3.4s} axb5 {-0.23/12 6.8s} 21. Rxa8 {+0.34/11 3.3s}
Qxa8 {-0.31/13 1.8s} 22. Bxd6 {+0.49/11 2.7s} Re8 {-0.35/11 2.4s}
23. Bb4 {+0.49/9 4.5s} Qa4 {-0.51/12 8.2s} 24. d6 {+0.56/12 5.4s}
Kh8 {-0.37/14 3.6s} 25. Qc5 {+0.56/9 1.7s} c2 {-0.33/12 3.6s}
26. d4 {+0.55/12 9.4s} Qb3 {-0.45/11 7.5s} 27. d7 {+0.55/11 2.7s}
Bxd7 {-0.46/13 3.6s} 28. Bxc2 {+0.53/12 4.3s} Rxe1+ {-0.46/12 3.3s}
29. Bxe1 {+0.48/11 2.8s} Qf3 {-0.39/10 2.3s} 30. Qc3 {+0.47/10 8.9s}
Qe2 {-0.39/10 10s} 31. Bd2 {+0.49/11 5.0s} Bh3 {-0.38/10 3.5s}
32. Bd3 {+0.49/9 4.6s} Qg4 {-0.38/9 8.4s} 33. Be1 {+0.47/8 9.7s}
Qxd4 {-0.33/8 5.7s} 34. Qc6 {+0.37/8 7.9s} Qd7 {-0.23/8 3.9s}
35. Qa8+ {+0.29/8 4.4s} Qc8 {-0.24/8 4.8s} 36. Qa5 {+0.33/7 5.3s}
Bd7 {-0.23/7 6.8s} 37. Bxb5 {+0.26/7 7.0s} Bxb5 {-0.17/7 4.7s}
38. Qxb5 {+0.22/7 2.0s} h5 {-0.14/6 5.2s} 39. Bd2 {+0.18/6 7.0s}
Kh7 {-0.16/6 9.6s} 40. Qd5 {+0.20/5 6.4s} Qc2 {-0.16/6 5.5s}
41. Be3 {+0.18/6 5.3s} Qb1+ {-0.16/6 4.8s} 42. Kg2 {+0.20/6 2.7s}
Qb4 {-0.17/6 5.1s} 43. h3 {+0.20/6 6.9s} Qe7 {-0.18/5 4.5s}
44. Kg1 {+0.19/5 5.5s} Qe5 {-0.18/5 5.6s} 45. Qb7 {+0.20/5 4.9s}
Qa1+ {-0.18/5 5.0s} 46. Kg2 {+0.22/6 5.1s} Qb2 {-0.19/6 4.8s}
47. Qf7 {+0.23/6 5.0s} Qf6 {-0.18/6 4.8s} 48. Qd7 {+0.21/6 4.6s}
Kg8 {-0.19/6 5.3s} 49. Qe8+ {+0.25/6 5.4s} Kh7 {-0.17/6 2.8s}
50. Qe4 {+0.17/6 4.7s} Qe5 {-0.16/6 7.2s} 51. Qc4 {+0.17/5 5.3s}
Qe7 {-0.15/5 5.0s} 52. Qd5 {+0.17/5 4.8s} Qe5 {-0.18/5 5.0s}
53. Qb7 {+0.22/6 4.5s} Qb2 {-0.16/5 5.0s} 54. Qf7 {+0.21/6 5.5s}
Qe5 {-0.15/6 5.0s} 55. Kh2 {+0.16/5 5.1s} h4 {-0.04/6 4.1s}
56. Qf4 {+0.14/6 4.9s} hxg3+ {-0.04/6 3.3s} 57. Kxg3 {+0.05/6 5.1s}
Qd5 {-0.03/5 7.5s} 58. Qh4+ {+0.09/5 4.5s} Kg8 {-0.03/6 3.2s}
59. Qg4 {+0.05/5 5.3s} Kh7 {-0.03/5 6.4s} 60. Qh4+ {+0.08/5 5.1s}
Kg8 {-0.01/6 3.5s} 61. Qg5 {+0.02/5 5.1s} Qxg5+ {0.00/6 6.9s}
62. Bxg5 {+0.02/5 2.8s} Kf7 {-0.02/5 5.0s} 63. Kg4 {+0.03/5 7.2s}
Bf8 {-0.01/5 5.0s} 64. Be3 {+0.03/5 5.0s} Be7 {-0.02/5 5.0s}
65. Bg5 {+0.03/5 5.0s} Bc5 {-0.01/5 5.0s} 66. Be3 {+0.02/5 5.0s}
Be7 {-0.01/5 4.8s, Draw by adjudication} 1/2-1/2

[Event "My Tournament"]
[Site "HaceTourney"]
[Date "2019.06.07"]
[Round "1"]
[White "lc0.Net.42475-Qdouble"]
[Black "lc0.Net.42475"]
[Result "1-0"]
[ECO "A00"]
[Opening "Mieses Opening"]
[PlyCount "118"]
[Termination "adjudication"]
[TimeControl "5+5"]

1. d3 {book} g6 {book} 2. c3 {book} d6 {book} 3. e4 {+0.08/6 4.0s}
Nf6 {+0.04/6 3.4s} 4. g3 {+0.04/7 4.5s} Bg7 {+0.03/7 4.4s} 5. Bg2 {+0.02/7 4.0s}
O-O {+0.03/7 5.0s} 6. Ne2 {+0.05/7 4.4s} e5 {0.00/7 5.3s} 7. c4 {+0.08/8 7.8s}
c5 {+0.01/7 5.2s} 8. Nbc3 {+0.03/7 5.0s} Nc6 {+0.02/7 5.3s}
9. O-O {+0.04/7 3.4s} a6 {-0.01/7 6.2s} 10. Nd5 {+0.09/7 5.8s}
Nxd5 {0.00/8 3.3s} 11. cxd5 {+0.08/8 2.9s} Nd4 {-0.03/8 3.8s}
12. Nxd4 {+0.12/8 3.6s} exd4 {-0.05/7 3.4s} 13. Bf4 {+0.09/7 9.2s}
f5 {-0.03/7 7.9s} 14. Qd2 {+0.14/8 3.1s} fxe4 {-0.06/8 4.0s}
15. Bxe4 {+0.13/7 3.0s} b5 {-0.01/8 7.1s} 16. b3 {+0.01/8 8.6s}
Bh3 {+0.12/7 4.7s} 17. Rfe1 {-0.09/7 2.9s} Ra7 {+0.29/8 3.0s}
18. Bg5 {-0.18/8 5.3s} Qb8 {+0.37/7 6.0s} 19. a4 {-0.28/7 5.8s}
bxa4 {+0.42/8 3.2s} 20. bxa4 {-0.28/8 3.0s} Rb7 {+0.31/7 3.5s}
21. Bf4 {-0.16/7 3.1s} Rff7 {+0.24/7 8.9s} 22. Qc2 {-0.09/7 6.4s}
Rb4 {+0.27/8 5.6s} 23. a5 {-0.20/7 8.3s} Bf8 {+0.33/7 2.9s}
24. Reb1 {-0.21/8 2.8s} Rfb7 {+0.29/8 4.4s} 25. Rxb4 {-0.25/8 3.7s}
Rxb4 {+0.33/8 3.2s} 26. Qd1 {-0.29/8 3.7s} Rb2 {+0.44/9 4.2s}
27. Bg2 {-0.32/9 4.2s} Bd7 {+0.40/8 5.0s} 28. Be4 {-0.31/8 5.0s}
Qb3 {+0.39/9 5.6s} 29. Qf1 {-0.29/8 3.8s} Qc2 {+0.41/8 3.9s}
30. h4 {-0.38/8 7.9s} Bg4 {+0.51/8 5.0s} 31. Re1 {-0.41/9 5.3s}
Bh3 {+0.51/9 5.8s} 32. Bg2 {-0.44/10 2.7s} Bf5 {+0.53/9 3.5s}
33. Be4 {-0.41/9 2.5s} Bg4 {+0.48/9 7.6s} 34. Qg2 {-0.28/8 12s}
Qc3 {+0.35/8 6.9s} 35. Rf1 {-0.09/8 2.7s} c4 {+0.27/8 4.6s}
36. Rc1 {-0.14/8 5.3s} Qxa5 {+0.22/8 2.8s} 37. Rxc4 {0.00/9 4.9s}
Rb1+ {+0.06/9 8.6s} 38. Kh2 {+0.26/9 3.5s} Qe1 {-0.13/8 2.4s}
39. f3 {+0.32/9 4.3s} Bd7 {-0.22/8 3.8s} 40. Rc7 {+0.46/8 9.7s}
Bf5 {-0.32/8 7.3s} 41. Bxf5 {+0.40/8 3.4s} gxf5 {-0.36/9 2.5s}
42. Rc8 {+0.38/8 4.0s} Kf7 {-0.26/8 4.4s} 43. Rc7+ {+0.40/8 5.2s}
Kg8 {-0.39/8 3.1s} 44. Rc6 {+0.65/8 3.9s} Ra1 {-0.46/7 8.9s}
45. h5 {+0.56/7 9.6s} a5 {-0.45/7 5.2s} 46. Kh3 {+0.84/7 2.4s}
Be7 {-0.94/7 8.6s} 47. Bxd6 {+1.12/7 3.9s} Bxd6 {-1.16/7 2.3s}
48. Rxd6 {+1.15/7 3.1s} Kf7 {-1.22/7 7.5s} 49. Rd7+ {+1.76/8 4.7s}
Kf6 {-1.76/7 4.0s} 50. Rxh7 {+2.34/7 4.6s} a4 {-2.40/6 6.2s}
51. d6 {+3.35/7 5.2s} f4 {-2.96/6 5.1s} 52. d7 {+4.55/7 6.6s} Qa5 {-3.42/6 4.1s}
53. gxf4 {+8.68/5 5.3s} Qf5+ {-5.35/4 5.2s} 54. Qg4 {+14.02/5 6.0s}
Rh1+ {-9.36/4 4.2s} 55. Kg2 {+17.25/5 5.9s} Rg1+ {-10.95/4 5.6s}
56. Kxg1 {+35.98/4 4.4s} Qxg4+ {-127.99/2 5.7s} 57. fxg4 {+127.99/2 3.6s}
a3 {-127.99/2 4.8s} 58. d8=Q+ {+127.99/4 8.6s} Ke6 {-127.99/2 0.003s}
59. h6 {+127.99/2 5.3s} a2 {-127.99/2 0.002s, White wins by adjudication} 1-0


```

Have fun testing.

### CODE REVIEW

**Comment by RedDenver** [comment]
This was discussed in issue #186

**Comment by MelleKoning** [comment]
Thanks or the update @RedDenver I just got here via the #875 

The interesting thing about the example game above (the win) is indeed the accuracy difference (even on these low node counts) and the difference in evaluation of white and black to the end of the game. That is, notice that the white evaluation + is continuously higher then the - eval of black.

Could that bigger difference be related to the current existing 'sticky-endgame' parameter (default true) that will propagate a very high Q more accurately to the root node with double than float?

**Comment by borg323** [comment]
There is also issue #328 and pr #349

**Comment by MelleKoning** [comment]
Thanks @borg323  I picked those changes floats to doubles up as well plus one extra declaration somewhere.

**Comment by koedem** [comment]
I doubt that there will be much of a difference in such low time controls though since N is rather small.
For TCEC time controls on the other hand I could see it helping. (or maybe not, would need tests which is tough with those time controls)

**Comment by zz4032** [comment]
Current master vs master_PR878:
```
   # PLAYER                 :  RATING  ERROR  LOS(%)   GAMES  DRAWS(%)
   1 lc0.net.42850          :     0.0   ----    74.8    5410      68.2
   2 lc0.net.42850_PR878    :    -1.7    5.1     ---    5410      68.2

White ELO advantage = 4.5
Draw rate (equal opponents) = 68.2 %
```
Match stopped randomly. Average node number: ~1460 nodes/move.
Cutechess settings: `tc=2.4+0.01 option.MoveOverheadMs=0 timemargin=1000` (time losses disabled) `-resign movecount=3 score=550   -draw movenumber=1 movecount=10 score=5`
LC0 Parameters: `option.Threads=1 option.Backend=cudnn-fp16 option.MinibatchSize=64` + 6-man-TBs + some 7-man

**Comment by Naphthalin** [comment]
This PR seems outdated due to the change to WDL (which would further increase the memory usage when used with doubles), and didn't produce any positive results. I therefore recommend closing this PR, as a new implementation of this is easier than updating the PR anyway.

**Comment by MelleKoning** [comment]
Agreed

**Comment by borg323** [comment]
Actually I think there is still interest in this from people interested in long analysis that have lots of memory. At least I see a occasional comments on discord that seem to imply so. Maybe revive this as a build configuration option?

**Comment by AlexGreason** [comment]
There's been some additional discussion of this, and one important piece of information (see [https://discordapp.com/channels/425419482568196106/438088534755377204/704889058190557194](url) and surrounding discussion) is what the NPS impact is - could this be rebased on master so that we can get this information?

**Pull request closed without merging**
