### PR TITLE
In smooth TM, use piggybank when it seems like the bestmove can be overtaken.

### LINKED ISSUE #1582: Smooth time manager should use piggybank then the eval for the current bestmove rapidly drops
In TCEC 2021 DivP game 10 (vs Stockfish), Lc0 found the move 27.Bxf8 which initially had a very high eval. Later during the search, Lc0 found a tactical refutation so the eval started to drop rapidly. 

However, Lc0 still made the move before Q dropped low enough for this move not to be the best, making possibly blunder move.

In such cases, it makes sense to trigger piggybank time usage.

Similar behaviour may be useful when some of the moves that are currently not the best, start to rapidly raise eval.

### PR DESCRIPTION
**Pull request by mooskagh**
Should help against this:
image

Not tested, likely also fixes #1582.

### CODE REVIEW

**Comment by mooskagh** [comment]
Example where it worked.

image

**Comment by mooskagh** [comment]
Looking at times where this logic triggered at WCCC, it didn't help, gave up too early. 

Example from WCSC R4 game vs Ginkgo:

image

**Comment by mooskagh** [comment]
image
Example where it did help!

**Comment by Naphthalin** [comment]
Do we plan on using/maintaining the smooth time manager any time soon?

**Review by borg323 — APPROVED** [review]

**Pull request merged**
