### PR TITLE
Easily run latest releases of lc0 and client using NVIDIA docker

### PR DESCRIPTION
**Pull request by vochicong**
I've make a repo
https://github.com/vochicong/lc0-docker
that help you easily run the latest versions of lc0 and the client under docker.
Both CPU and GPU versions are available.

### CODE REVIEW

**Comment by DanielUranga** [comment]
Consider re-using the `danieluranga/leela_chess_zero-lc0_ubuntu_builder:0.0.4` image. Also probably it would be better to just add instructions to the wiki, and add a link to the nvidia docker documentation also.

**Comment by vochicong** [comment]
Do you have the link to Dockerfile of `danieluranga/leela_chess_zero-lc0_ubuntu_builder`?

**Comment by vochicong** [comment]
@DanielUranga It seems that the `danieluranga/leela_chess_zero-lc0_ubuntu_builder` image is created from https://github.com/LeelaChessZero/lc0/blob/master/.circleci/Dockerfile #101. This one looks good for CircleCi to build and test lc0, but not god for someones to run lc0 and the client to contribute for lc0 training.

**Comment by vochicong** [comment]
> Don't know what it is all about, but probably something useful. :)

Yes it is. It's actually running as a top **active user** at https://lczero.org/active_users.

**Pull request merged**
