### PR TITLE
New cuda backend without cudnn

### PR DESCRIPTION
**Pull request by borg323**

### CODE REVIEW

**Comment by ankan-ban** [comment]
great job @borg323. Not only this avoid dependency on cudnn library dlls, it's actually a tiny bit faster than cudnn backend on Titan RTX with 384x30 networks.

**Comment by ankan-ban** [comment]
Looks like there is some bug affecting bigger batch sizes, this crashes for me:
`lc0 benchmark --backend=cuda --minibatch-size=1024`

**Comment by borg323** [comment]
I also noticed some accuracy loss with `cude-fp16` that needs investigating.

**Comment by borg323** [comment]
The crashes should be fixed now, and the accuracy looks similar to cudnn-fp16 in my tests.

**Review by ankan-ban — APPROVED** [review]
Looks good.

**Pull request merged**
