### PR TITLE
Reduce record backend stored file size by a factor of 3.

### PR DESCRIPTION
**Pull request by Tilps**
This takes advantage of the specific pattern of requests made to any given computation to avoid having to store the entire list of requests.
It is a bit 'more' fragile, but given how fragile it already is, I think the disk space and load time savings are worth it.
10 million nodes search takes about 1GB file now meaning 40 million node searches are a plausible replay possibility.

Also make it more explicit that only the first instance of a hash value in the replay file is used.  This was needed to make the behavior correct, but its good to be clear anyway. (It also slightly reduces the memory usage at runtime during replay, even above the 3 fold reduction from reduced recording data.)

### CODE REVIEW

**Comment by borg323** [comment]
Wouldn't this be better done in the search/cache, just reading once from the backend?

**Comment by Tilps** [comment]
Much easier said than done... The first read happens in CachingBackend during ComputeBlocking.
The second and third are much further a field - I don't think I could plausibly get it down to one loop without changing CachingBackend API to be much more ugly. And I think getting that last factor of 2 (after the 2/3rds) is well worth the complexity in this corner case backend that only a handful of people are ever going to use and notice if it ever stops working...

**Comment by borg323** [comment]
The following gets rid of the last round (the more fragile one) and is ~5% faster with the random backend for me:
```
diff --git a/src/mcts/search.cc b/src/mcts/search.cc
index 6a771e8..733aa62 100644
--- a/src/mcts/search.cc
+++ b/src/mcts/search.cc
@@ -1472,26 +1472,24 @@ void SearchWorker::FetchSingleNodeResult(NodeToProcess* node_to_process,
   // ...and secondly, the policy data.
   // Calculate maximum first.
   float max_p = -std::numeric_limits<float>::infinity();
-  for (auto edge : node->Edges()) {
-    max_p = std::max(max_p, computation_->GetPVal(
-                                idx_in_computation,
-                                edge.GetMove().as_nn_index(
-                                    node_to_process->probability_transform)));
-  }
   // Intermediate array to store values when processing policy.
   // There are never more than 256 valid legal moves in any legal position.
   std::array<float, 256> intermediate;
-  float total = 0.0;
   int counter = 0;
   for (auto edge : node->Edges()) {
     float p = computation_->GetPVal(
         idx_in_computation,
         edge.GetMove().as_nn_index(node_to_process->probability_transform));
+    intermediate[counter++] = p;
+    max_p = std::max(max_p, p);
+  }
+  float total = 0.0;
+  for (int i = 0; i < counter; i++) {
     // Perform softmax and take into account policy softmax temperature T.
     // Note that we want to calculate (exp(p-max_p))^(1/T) = exp((p-max_p)/T).
-    p = FastExp((p - max_p) / params_.GetPolicySoftmaxTemp());
-
-    intermediate[counter++] = p;
+    float p =
+        FastExp((intermediate[i] - max_p) / params_.GetPolicySoftmaxTemp());
+    intermediate[i] = p;
     total += p;
   }
   counter = 0;
```

**Comment by Tilps** [comment]
Yes, I was thinking much the same thing. And I would be happy to see that as a separate PR - in which case I can remove the 3rd if statement as a follow up.
However random backend is a likely poor choice for benchmarking here, since it calls HashCat in its computation getters, where for real backends its just an array indexing operation.
So I wouldn't get too excited about that 5%...

**Comment by borg323** [comment]
I tested with cache, so the last GetPVal should have been just a cache lookup. Anyway, we'll find out soon enough.

**Comment by borg323** [comment]
BTW, the easy way is to skip the first round of calls if NNCacheSize=0, but the added complexity will probably not be worth it in normal use.

**Comment by Tilps** [comment]
> I tested with cache, so the last GetPVal should have been just a cache lookup. Anyway, we'll find out soon enough.

A given CachingComputation either uses the cache or does not use the cache for a given input for its lifetime - it doesn't switch to using the cache part way through.

**Comment by borg323** [comment]
It looks to me that CachingComputation::ComputeBlocking() calls the Get?Val functions even if the cache size is 0, which is how you get the 1st round.

**Comment by Tilps** [comment]
I was meaning that regardless of whether caching is enabled or not - the number of calls received by the parent computation for a given sample index is either 0 or all of them. There is no case that some of the calls to a CachingComputation for a specific sample index go through to parent, and some don't.

**Pull request merged**
