### PR TITLE
renamed smart-pruning-aggresiveness option to smart-pruning

### PR DESCRIPTION
**Pull request by borg323**
As @mooskagh asked. Only the option is renamed, the variable names are left as they were.

### CODE REVIEW

**Comment by dubslow** [comment]
I'd like a day or so to submit an alternative

**Comment by jjoshua2** [comment]
Alternative naming and stuff or a whole new algorithm? I've been running
clop tuning on this again and might have a little better param for a head 2
head test...

**Comment by dubslow** [comment]
Alternative names, algorithm untouched

**Comment by mooskagh** [comment]
Ok, maybe just `smart-pruning` is bad too.. But aggressiveness is kind of wrong, because smaller number means higher "aggressiveness". Maybe `forlorn-move-cutting` as discussed? :)
Or 'move-cutting-value` ?

**Comment by borg323** [comment]
Renamed option to `unlikely-moves-avoidance` and inverted the value. Default now is 1.47 (approximately 1/0.68). Did not rename variables to minimize delta with other patches people are working on.

**Comment by borg323** [comment]
New option name --futile-search-aversion, thanks to \@JokingGiantKnight on discord.

**Comment by mooskagh** [comment]
Looks good! Feel free to merge when commit checks finish and unblock the button.

**Pull request merged**
