### PR TITLE
 Node goes on a diet (#13). Remove V and W, use power decay averaging (#32)

### PR DESCRIPTION
**Pull request by mooskagh**
Also remove extra virtual loss.

### CODE REVIEW

**Comment by mooskagh** [comment]
Game board was long time removed (end of April), it made it go 112 -> 56 bytes.

Removing unexpanded nodes is what I'm working on actively right now.
(proof: stats of total children and visited children after doing 80000 nodes from startpos:
https://docs.google.com/spreadsheets/d/1LoBEjxZ0xqwNdV9OFP36RsxyB2_suGNdySq8Hr4IDRU/edit#gid=0, generated this morning)

But just as I was low energy and sleepy in the morning, wanted to do something small and easy which required very little concentration.

**Comment by mooskagh** [comment]
Tests whether it affects strength of the gameplay (on default settings) are still in progress.

**Comment by Videodr0me** [comment]
If you check recent testing on my experimental site, power decay averaging does not work well for high visit searches (looses elo). I am still investigating this, but i would not have very high hopes for this. But i have some new data on some other improvements soon, which look very good and scale well. Thats also motivation for the following comment which is not directly related to this PR:

@mooskagh Please do not remove unexpanded children just yet.  They might become extremely useful and even though they have some computational and space overhead these may potentially be offset by some real elo gains. Let me explain (this is not advocating against removing them, but maybe do that a little later):

1) I rearranged the code to test for terminal nodes in the unexpanded children creation loop. This allows Leela to see mates and other terminal positions one visit earlier as the result can be backpropagated to the parent node right away.

2) This plays well with certainty propagation another small elo gain (more so if TB get integrated). That might be interesting for official LC0 in the future (not now obiously)

3) A new method called tree-balancing relies on some stats calculated there and stores it in these nodes. This methods inital testing is very promising (and scales well with high visit searhes). More info soon.

Just, wait a little so see how all these tests turn out in the end.

**Comment by killerducky** [comment]
@mooskagh @Videodr0me Is there an update here? The last comment by Videodr0me says this makes the engine worse at high visit counts. I'm not sure which version of the code is in this PR, but I see a table that says for 10K visits, "Elo: -11.12 LOS: 4.94%"

Was there new test data?

**Comment by mooskagh** [comment]
It only makes a difference when values of those parameters are not 1.0.
With the default values of 1.0 it should (in theory) not make a difference. I'll do a proper test though today.

As for @Videodr0me's comment, he meant that with non-1.0 settings it was expected to improve strength but it doesn't.

**Comment by dubslow** [comment]
I'm thinking, between this and the dynamic temp thing, that we should make it possible to add "silent" options, which are options which exist but aren't displayed by `--help`. Then these two backpropogate options, and the two evaltemp options can remain usable for those interested without unnecessarily confusing people in need of `--help`.

**Comment by mooskagh** [comment]
We should aim to reduce code complexity, not --help complexity. I've never heard anyone complaining about --help being too long so far.

Therefore I'm for aggressive removal of all options of non-proved usefulness. If needed later, we can add that later.
Unused parameters really slow down code understanding and adding of new features.

**Comment by Videodr0me** [comment]
@mooskagh Agree, couldn't make it work, doubtful it ever will, get rid of it.

**Pull request merged**
