### PR TITLE
fixe setoption behaviour.

### PR DESCRIPTION
**Pull request by ContradNamiseb**
This pr partially fixes issue #1843

### CODE REVIEW

**Comment by ContradNamiseb** [comment]
Here is an e.g of how it now works:

 `      _
|   _ | |
|_ |_ |_| v0.31.0-dev+git.dirty built Jan 21 2024
Found configuration file: C:\Users\cenam\Documents\lc0_onnxtest/lc0.config
setoption name cpuct threads value 2.14 2
setoption name cpuct hash value 2.14 2
error Unknown option: hash
setoption name cpuct threads value 2.14 2
setoption name cpuct threads value 2.14
error Mismatched number of names and values
setoption name cpuct value
error Provide a value for the option
setoption name  value 3
error An option name must be provided
value livelogstats value true
error Unknown command: value livelogstats value true
setoption value livelogstats value true
error An option name must be provided`

**Comment by mooskagh** [comment]
It doesn't look like the code does what you described.  
And I don't think that the behaviour you described is what's needed.

```
setoption name a name b value 1 value 2
```

should set an option "`a name b`" to value "`1 value 2`"

**Comment by ContradNamiseb** [comment]
> It doesn't look like the code does what you described. And I don't think that the behaviour you described is what's needed.
> 
> ```
> setoption name a name b value 1 value 2
> ```
> 
> should set an option "`a name b`" to value "`1 value 2`"

**Comment by ContradNamiseb** [comment]
Sorry meant to edit the comments not close the pr.  I changed the described behavior of the code after talking with borg he recommended to keep this current changes in the pr.

**Comment by ContradNamiseb** [comment]
@mooskagh this is what I originally had.

```void OptionsParser::SetUciOption(const std::string& name,
                                 const std::string& value,
                                 const std::string& context) {
   if (name.empty()) {
      throw Exception("An option name must be provided");
    } else {
        // Split the names and values by space.
        std::vector<std::string> names = SplitString(name, ' ');
        std::vector<std::string> values = SplitString(value, ' ');
        // Check that the number of names and values match
        if (names.size() != values.size()) {
            throw Exception("Mismatched number of names and values");
        }
        // Set the UCI options for each name-value pair
        for (size_t i = 0; i < names.size(); ++i) {
            const std::string& name = names[i];
            const std::string& value = values[i];
            auto option = FindOptionByUciName(name);
            if (option) {
            option->SetValue(value, GetMutableOptions(context));
            } else {
            // If name is not valid throw an error.
            throw Exception("Unknown option: " + name);
            }
        }
        return;
    }
}```

**Comment by mooskagh** [comment]
It doesn't look to me that the code snippet from your latest comment does what is needed either.

**Pull request closed without merging**
